mongodb/mongodb-atlas-kubernetes

- .github/workflows/push-test.yml
- test/int/suite_test.go
Running unit tests from GitHub action.
So far I've moved the `suite_test.go` to `tests/int` to separate such tests from unit tests. This will be reviewed later when we address integration tests.
Note, that running locally using `act -j unit-test` is super-slow as Go is installed each time - this may be addressed in future
> CLOUDP-78443: GitHub action for running unit tests

- .golangci.yml
- main.go
- pkg/api/v1/atlascustomresource.go
- pkg/api/v1/atlasproject_types.go
- pkg/controller/atlas/api_error.go
- pkg/controller/atlas/connection.go
- pkg/util/set/identifiable_test.go
- test/int/suite_test.go
This PR adds a set of linter rules almost as strict as was used in `atlas-osb`; some rules were relaxed due to the differences in architecture (use of `init()` functions, global variables, etc.)
> Add golangci-lint settings

- .golangci.yml
As discussed with the team we won't use gofumpt as a mandatory linter.
It can be used locally still.
> Removing gofumpt from the list of mandatory linters

- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/customresource/customresource.go
- pkg/controller/workflow/result.go
This PR handles the situation when the AtlasProject CR has been removed - no retry must happen in this case.
Note, that handling the deletion for the AtlasProject in Atlas is a TODO as we need to investigate all the scenarios (removing the project if there are dependent clusters for example)
> CLOUDP-79534: don't reconcile if the Project has been removed

- pkg/controller/atlas/api_error.go
- pkg/controller/atlasproject/project.go
There was a bug that the code didn't handle the "get project by name" properly. This returns 401 and it seems handling to error code is the best instead of HTTP header
> CLOUDP-79537: catch the API error if the project already exists

- test/int/integration_suite_test.go
- test/int/project_test.go
Rejected the idea of having a package per int test as it seems logical to have a single `suite_test.go`  per all the tests and avoid duplication of `project_suite_test.go`, `cluster_suite_test.go` (as they will all be the same)
> Moving test files

- Makefile
- Encapsulate most env variables to their respective targets, hopefully improving readability
- Add self-documentation via ##
New output when run without a target:
```
$ make
Usage: make <OPTIONS> ... <TARGETS>
Available targets are:
help                       Show this help screen
all                        Build all binaries
int-test                   Run integration tests
manager                    Build manager binary
run                        Run against the configured Kubernetes cluster in ~/.kube/config
uninstall                  Uninstall CRDs from a cluster
deploy                     Deploy controller in the configured Kubernetes cluster in ~/.kube/config
manifests                  Generate manifests e.g. CRD, RBAC etc.
fmt                        Run go fmt against code
vet …
```
> CLOUDP-80623: Improve Makefile

- README.md
- pkg/controller/atlas/api_error.go
- pkg/controller/atlascluster/atlascluster_controller.go
- pkg/util/testutil/customresources.go
- test/int/cluster_test.go
This fixes cluster deletion: uses the `spec.Name` instead of the resource `Name`.
Also moves the testing logic for cluster deletion to `afterRun` to avoid double calls to cluster removal. Then waits until the cluster is removed and removes the project
> CLOUDP-81188: fix deletion of Atlas Cluster

- CODE_OF_CONDUCT.md
- LICENSE
- SECURITY.md
This PR brings the repo in line with other mongodb public repos, main changes:
- add a SECURITY advisor
- add a CODE_OF_CONDUCT
- Correct the LICENSE file to keep the place holders
> docs: add SECURITY and CODE_OF_CONDUCT

- .gitattributes
This PR restricts line endings for `go.sum` & `go.mod`, as well as allows Github to auto-merge _most_ `go.sum` conflicts
> Add .gitattributes for go.sum & go.mod

- pkg/util/kube/kube.go
- pkg/util/kube/kube_test.go
This PR prepares some groundwork for the next one that creates the Connection Secret.
As discussed with the team the name of the secrets will be:
`<project-name>-<cluster-name>-<db-user>` 
and also the secret will have the label for cluster name.
Taking the user input and using as K8s identifiers/label values is risky so some "normalization" work is done.
> CLOUDP-82588: normalize K8s ids

- pkg/controller/connectionsecret/ensuresecret.go
- pkg/controller/connectionsecret/ensuresecret_test.go
- pkg/controller/connectionsecret/listsecrets.go
- pkg/controller/connectionsecret/listsecrets_test.go
This PR depends on https://github.com/mongodb/mongodb-atlas-kubernetes/pull/145
This PR adds support for getting the connection secrets either by cluster name or by user name.
This will be necessary while cleaning the secrets on changes (mostly removals) of cluster/dbUser resources
> CLOUDP-82588: list secrets by cluster or username

- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- config/rbac/clusterwide/role.yaml
- config/rbac/namespaced/role.yaml
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
Forgot to add Secrets permissions to let Operator create/delete secrets
(Integration tests pass as seems permissions are not tested there while working with envtest)
> Fix secret permissions

- .github/actions/gen-install-scripts/Dockerfile
- .github/actions/gen-install-scripts/action.yml
- .github/actions/gen-install-scripts/entrypoint.sh
- .github/workflows/release-branch.yml
- .github/workflows/test.yml
Adds support for bundle generation during the release
I generated the [release branch](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/159) and tried to install it into the OLM. Everything was ok, though the deployment didn't succeed (which makes sense as we haven't released the new image yet)
I edited the deployment and change the image to `mongodb/mongodb-atlas-kubernetes-operator-prerelease:CLOUDP-84352-olm-bundle-release-5a84c7e` - after this it succeeded.
```
➜  mongodb-atlas-kubernetes git:(release/0.21.0) make bundle-build BUNDLE_IMG=antonlisovenko/test-bundle:v0.21.0
docker build -f bundle.Dockerfile -t antonlisovenko/test-bundle:v0.21.0 .
Sending build context to Docker daemon  379.5MB
Step 1/14 : FROM scratch
--->
Step 2/14 : LABEL …
```
> CLOUDP-84352: generate OLM bundle during release process

- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- pkg/controller/atlascluster/atlascluster_controller.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- test/int/dbuser_test.go
Adds support for database user removal. Ensures connection secrets are removed as well.
In addition checks for the database user statuses to contain connection secrets information - this was missed in the previous PR
> CLOUDP-82591: support removing the database users

- config/manager/manager.yaml
- main.go
- pkg/controller/atlas/connection.go
- pkg/controller/atlascluster/atlascluster_controller.go
- pkg/util/kube/kube.go
- pkg/util/kube/kube_test.go
- test/int/integration_suite_test.go
- test/int/project_test.go
This fixes the issue with "global secret" when Operator used the Pod name instead of deployment. In this case it expected the secret with the name "mongodb-atlas-operator-97cd985f5-whgrx-api-key" instead of "mongodb-atlas-operator-api-key"
No tests for this so far, checked manually:
```
2021-03-11T14:25:03.416Z	DEBUG	controllers.AtlasProject	AtlasProject connection Secret is not specified - using the Operator one: mongodb-atlas-system/mongodb-atlas-operator-api-key	{"atlasproject": "mongodb-atlas-system/my-project"}
```
> CLOUDP-84457: fix for global secret

- pkg/api/v1/atlasdatabaseuser_types.go
- pkg/controller/atlasdatabaseuser/databaseuser.go
- pkg/controller/workflow/reason.go
- test/int/dbuser_test.go
The PR adds validation code for `scopes` field in AtlasDatabaseUser spec. The reconciliation fails if the cluster with this name doesn't exist in Atlas.
Some customer-facing logic: it's ok if the AtlasCluster and AtlasDatabaseUser are created in parallel (say both configs are in the same script) - in this case AtlasDatabaseUser validation may fail the first time as the Cluster may not exist yet - the retry will fix the problem which should be ok.
> CLOUDP-82590: validate 'scopes' field in AtlasDatabaseUser 

- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- main.go
- pkg/api/v1/atlasdatabaseuser_types.go
- pkg/api/v1/status/atlasdatabaseuser.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatabaseuser/databaseuser.go
- pkg/controller/atlasproject/atlasproject_controller.go
- test/int/dbuser_test.go
- test/int/integration_suite_test.go
Depends on https://github.com/mongodb/mongodb-atlas-kubernetes/pull/172
This PR adds the code to watch the database user passwords Secrets. As soon as those secrets are changed by the user - the db user reconciliation is triggered and the update request is sent to Atlas.
Note, that to support this we have to keep the state of the password secret in the database user status. This is necessary as the controller needs to know when the passwords have changed as current "compare db users specs" code won't give this information (Atlas doesn't return passwords for db users in GET requests).
> CLOUDP-82709: watch password secrets

- main.go
- test/int/integration_suite_test.go
As discussed before we need to decrease the sync period to support marking resources (IP Access Lists, database users) as expired sooner than later.
> CLOUDP-82593: lower sync period

- config/manager/manager.yaml
- config/managerwithproxy/manager_auth_proxy_patch.yaml
- config/rbac/clusterwide/auth_proxy_role_binding.yaml
- config/rbac/clusterwide/kustomization.yaml
- config/rbac/clusterwide/role_binding.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/namespaced/auth_proxy_role_binding.yaml
- config/rbac/namespaced/kustomization.yaml
- config/rbac/namespaced/role_binding.yaml
- config/rbac/service_account.yaml
- config/release/base/namespaced/manager_watched_namespace_patch.json
- deploy/namespaced/namespaced-config.yaml
- main.go
This PR makes the changes to align the configuration with the Helm chart (https://github.com/mongodb/helm-charts/pull/25):
* adds support for the service account
* increases the limits resources
* doesn't create the CluterRole `metrics-reader` as it's not required by the Operator
* renames `WATCHED_NAMESPACE` to `WATCH_NAMESPACE` as the later is a standard naming in the other operators
> CLOUDP-84606: helm support

- pkg/controller/atlascluster/cluster.go
- pkg/controller/atlascluster/cluster_test.go
- test/int/cluster_test.go
- test/int/dbuser_test.go
- test/int/project_test.go
This PR focuses on more complicated testing of the clusters. Due to the size only the creation is happening - the update will be addressed in the next PR (found some issues there).
The changes were reviewed and agreed on with Pavel p2p.
* fixed the situation when the user specifies the `providerSettings.regionName` together with `replicationSpecs`. In this case Atlas accepts the update request but erazes the former field so the infinite reconciliation happens as `ClustersEqual` method constantly returns false.
* added more checks to the integration test to check all the fields
* more unit tests to make sure the `MergedCluster` and `ClustersEqual` work correctly
* increased the timeout for project create/update as 20 seconds is not enough often
> CLOUDP-83733: more tests on clusters (create only)

- pkg/controller/atlascluster/cluster.go
- pkg/controller/atlascluster/cluster_test.go
- test/int/cluster_test.go
This PR adds more complicated scenarios for cluster update. It also fixes the problem when the removal of `replicationSpecs[i].regionsConfigs['X']` is not handled properly.
> CLOUDP-86187: cluster update (replicationSpecs)

- README.md
As a suggestion: to keep the quickstart section - otherwise the page looks too empty and also many people will benefit from the quickstart without going to the docs.
> CLOUDP-86200: link to the docs

- pkg/api/v1/atlascluster_types.go
- test/int/dbuser_test.go
- test/int/project_test.go
Using M2 cluster instances for user integration tests
As a result of this optimization the tests finish in 10 minutes instead of 20
> CLOUDP-86590: using M2 clusters for some tests

- Makefile
The latest V4 version of `yq` has new syntax,
this small change fixes issues caused by the migration.
Along with this change local `yq` should be updated to the latest release.
This can be done via brew: `brew upgrade yq` (https://pypi.org/project/yq/)
P.S. there is a solution which doesn't involve the update. The use of V3 is not recommended but possible.
In case V3 syntax is left as it is I suggest to update `start-guide.md` with: `brew install yq@3`
> Update yq to version 4

- pkg/util/httputil/loggedclient.go
This PR adds the capability to log all non-empty request bodies sent to Atlas. This flag is hardcoded in the code and serves solely for dev/debugging purposes. One use case is when we need to intercept some API calls we make to Atlas to file HELP tickets. This allows to reproduce the payload we send to them.
> Optionally logging HTTP request body

- Makefile
- docs/dev/start-guide.md
- scripts/deploy.sh
Our `make deploy` is broken - for some reasons `act -j ..` doesn't work for local custom actions.
Changed this to a script directly - this is anyway faster than calling `act`
> Fix "make deploy"

- main.go
- pkg/controller/atlas/connection.go
- pkg/controller/atlascluster/atlascluster_controller.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasproject/atlasproject_controller.go
- test/int/integration_suite_test.go
- test/int/project_test.go
This PR allows the user to override the global API key Secret by passing the `global-api-secret-name` argument to the container. If the flag not provided - the name defaults to the `<deployment_name>-api-key`
As this cannot be tested by integration tests I've tested this manually: changed the deployment spec to the following:
```
- args:
- --atlas-domain=https://cloud-qa.mongodb.com
- --health-probe-bind-address=:8081
- --metrics-bind-address=127.0.0.1:8080
- --leader-elect
- --global-api-secret-name=the-global-key
command:
- /manager
```
and ensured, that the new Secret was used by the Operator instead of the default one
> CLOUDP-87735: global secret configuration

- pkg/controller/atlasproject/atlasproject_controller.go
I've added an extra check in the Delete method for Projects.
- I thought it makes sense to have this new check right after the first function comment
(so it is clear that that's a part of delete process)
- No error is thrown
> CLOUDP-88737: Do not try to delete non-existing Atlas projects

- config/manager/manager.yaml
- config/release/base/allinone/kustomization.yaml
- config/release/base/clusterwide/kustomization.yaml
- config/release/base/namespaced/kustomization.yaml
- config/release/base/namespaced/manager_watched_namespace_patch.json
- config/release/dev/dev_patch.json
- config/release/prod/prod_patch.json
- deploy/all-in-one.yaml
- deploy/clusterwide/clusterwide-config.yaml
- deploy/namespaced/namespaced-config.yaml
Removing the container for kube-proxy
Note, that we usually don't change the configs in `deploy` directory manually - this is done during the release.
But now I've decided to do it as this will fix the critical error for the users. Also the previous release 0.5.0 will still have kube-proxy - so we are changing the "dev" version only
> CLOUDP-86954: remove kube-proxy

- scripts/create_kind_cluster.sh
- test/e2e/config/kind.yaml
- test/e2e/configuration_test.go
- test/e2e/data/atlascluster_multiregion_aws.yaml
- test/e2e/data/atlascluster_multiregion_aws_update.yaml
- test/e2e/data/atlascluster_multiregion_azure.yaml
- test/e2e/data/atlascluster_multiregion_azure_update.yaml
- test/e2e/data/atlascluster_multiregion_gcp.yaml
Added different providers to e2e-tests
> CLOUDP-95652-additional-multiregional-test

- go.mod
- go.sum
- test/int/clusterwide/integration_suite_test.go
- test/int/integration_suite_test.go
I wanted to be able to run the integration tests and needed to reconfigure the Atlas domain being used to do so.
users can `export ATLAS_DOMAIN="https://cloud.mongodb.com"` to run the tests using the public Atlas platform.
Perhaps there are other places to modify, or a better way? Currently I'm hooking into the `package` `init` function to set the variable via an env var or use a default value.
Also, what's the best way to speed these tests up? Should I throw more ginkgo threads at them?
> Configurable integration domain

- scripts/create_kind_cluster.sh
- scripts/deploy.sh
This is a small patch to enable us to use clusters other than kind when deploying the operator.
> Specify registry for the operator image, and bypass kind cluster creation.

- Dockerfile
- Makefile
- config/rbac/clusterwide/role.yaml
* Added target for unit-tests
* Dockerfile now uses the same Makefile to build the manager
> Added target for unit-tests. Unified build for Docker

- .github/actions/gen-install-scripts/entrypoint.sh
- scripts/e2e_local.sh
This PR closes CLOUDP-111985. `sed` replaced with `awk` to allow script to run on both MacOS and Linux without any modifications.
> CLOUDP-111985: Made E2E cross-platform

- go.mod
- go.sum
- pkg/api/v1/status/condition.go
- pkg/controller/atlascluster/atlascluster_controller.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/validate/validate.go
- pkg/controller/validate/validate_test.go
- test/int/cluster_test.go
- test/int/clusterwide/dbuser_test.go
- test/int/dbuser_test.go
- test/int/project_test.go
This PR validates the new advancedCluster/regularCluster spec changes.
The validation functions for the other types isn't strictly required, but I think it's a good idea to have all resources showing the same conditions.
> Added validation for cluster resource

- .github/workflows/test.yml
- cmd/manager/main.go
- config/release/prod/prod_patch.json
With the latest upgrade of the atlas api library, it is now necessary to provide URL with trailing slash
> Fixed URL for the atlas operator client

- .github/actions/set-tag/entrypoint.sh
- .github/workflows/lint.yaml
- pkg/controller/atlasproject/atlasproject_controller.go
- test/int/cluster_test.go
- test/int/clusterwide/dbuser_test.go
- test/int/dbuser_test.go
Remove finalizer from the atlas project if connection secret is gone. Resolves: https://github.com/mongodb/mongodb-atlas-kubernetes/issues/425
> CLOUDP-113285: Remove finalizer from the atlas project if connection secret is gone

- Makefile
- cmd/manager/main.go
- test/int/clusterwide/integration_suite_test.go
This PR fixes incorrect version of PRODUCT_VERSION for the manager binary
> CLOUDP-119550: Fixed PRODUCT_VERSION for the manager

- pkg/controller/atlascluster/atlascluster_controller.go
closes [CLOUDP-115287](https://jira.mongodb.org/browse/CLOUDP-115287)
> CLOUDP-115287: Allow users not to specify TENANT when creating AtlasCluster resources

- pkg/controller/atlasdeployment/deployment.go
Added an ability to upgrade shared clusters. Closes: [CLOUDP-118355](https://jira.mongodb.org/browse/CLOUDP-118355)
> CLOUDP-118355: Shared cluster upgrade ability

- pkg/controller/watch/resource_watcher_test.go
Added unit tests for the ResourceWatcher.
Closes: [CLOUDP-119373](https://jira.mongodb.org/browse/CLOUDP-119373)
> CLOUDP-119373: Added unit tests for the ResourceWatcher

- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
- config/samples/atlas_v1_atlasproject.yaml
- config/samples/atlas_v1_atlasproject_with_maintenance_window.yaml
- pkg/api/v1/atlasproject_types.go
- pkg/api/v1/project/maintenancewindow.go
- pkg/api/v1/status/condition.go
- pkg/api/v1/zz_generated.deepcopy.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/maintenancewindow.go
- pkg/controller/atlasproject/maintenancewindow_test.go
- pkg/controller/workflow/reason.go
- pkg/util/testutil/maintenancewindow_matcher.go
- test/int/project_test.go
```
projectMaintenanceWindow:
dayOfWeek: 5
hourOfDay: 1
autoDefer: false
startASAP: false
defer: false
```
If no field specified, maintenance window is deleted (if it exists)
User must always specify at least `dayOfWeek`. `hourOfDay` is defaulted to 0 (midnight), `autoDefer` is defaulted to false
Only one of (`startASAP`, `defer`) can be true
`dayOfWeek`, `hourOfDay` and `autoDefer` represent the actual state of the window in Atlas 
`defer` and `startASAP` are used to send one request only (and then the user should reset them to `false`)
1. Check if window needs to be deleted
2. Check if window needs to be updated (`hourOfDay`, `dayOfWeek`)
1. If yes, update (`hourOfDay`, `dayOfWeek`, `autoDefer`) according to YAML spec
2. If no, check if `autoDefer` must be toggled (there is a specific …
> CLOUDP-126252: Maintenance Windows support

- pkg/controller/atlasdeployment/atlasdeployment_controller.go
Somehow I've missed quite a few name changes in the original request #556.
> Add missed deployment name changes

- .github/workflows/openshift-upgrade-test.yaml
- scripts/openshift-upgrade-test.sh
> Fixed Openshift test timeouts

- .github/workflows/openshift-upgrade-test.yaml
- Makefile
- go.mod
- pkg/api/v1/atlasdeployment_types_test.go
- pkg/controller/atlasdeployment/advanced_deployment.go
- pkg/controller/atlasdeployment/advanced_deployment_test.go
- pkg/util/toptr/toptr.go
- scripts/int_local.sh
- test/int/deployment_test.go
- Prevent changes of `instanceSize` if `autoscaling` is enabled for `compute` for the region
- Prevent changes of `diskSizeGB` if `autoscaling` is enabled for `diskGB`
closes: #648 & #649
> CLOUDP-133702: Prevent changing instanceSize and diskGB if autoscaling is enabled

- pkg/api/v1/atlasproject_types.go
X509CertRef is a ResourceRefNamespaced, which means it contains a name and a namespace. The name is only used to get the object while the namespace is discarded, This PR uses the namespace defined here to get the object while falling back to the project namespace to maintain backward compatibility.
This can break projects for people configuring the namespace differently that what's intended. It will only break if the configuration is initially wrong.
> use X509CertRef to get the namespace of the cert

- pkg/controller/atlasdeployment/advanced_deployment.go
- pkg/controller/atlasdeployment/advanced_deployment_test.go
- pkg/controller/atlasdeployment/instance_size.go
- pkg/controller/atlasdeployment/instance_size_test.go
- pkg/controller/validate/validate.go
- pkg/controller/validate/validate_test.go
- test/int/deployment_test.go
> CLOUDP-136586: Allow autoscaling instanceSize and diskSizeGB outside of the manually set instanceSize and diskSizeGB

- .github/workflows/integration-test-forked.yml
- .github/workflows/integration-test.yml
> CLOUDP-141993: Split integration test

- pkg/controller/atlasproject/private_endpoint.go
When there is an error with PEs the **privateEndpoints** status is missing. This change fixes that.
> Make sure PEs are always added to status

- .github/workflows/release-branch.yml
It looks like there is a [change in go-licenses which breaks the current release script](https://github.com/google/go-licenses/issues/128).
[The error](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/3601793096/jobs/6068003604) reads like this:
```
Package command-line-arguments does not have module info. Non go modules projects are no longer supported.
```
Need to investigate why this error appears and why now and maybe even do not merge this PR.
> Use go-licenses@v1.0.0 instead of the latest version

- pkg/controller/atlasproject/team_reconciler.go
> Fix usage of errgroup to sync team users

- .github/workflows/release-post-merge.yml
Temporarily disable image certification
> Temporarily disable image certification

- config/rbac/leader_election_role.yaml
Move `leases.coordination.k8s.io` to its own proxy-role rule
> Move leases.coordination.k8s.io to its own proxy-role rule

- Makefile
Default version from bundle at:
https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.0/hack/setup-envtest.sh
Is `kubebuilder-tools-1.19.2-darwin-arm64.tar.gz`, and that did not exist here:
https://storage.googleapis.com/kubebuilder-tools/
Version `1.26.1`, on the other hand, does exist.
> Upgrade testenv Kubernetes version

- .github/actions/build-push-image/action.yaml
- .github/actions/cleanup-pe/cleanall.go
- go.mod
- go.sum
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- test/e2e/actions/cloud/gcp.go
- test/e2e/actions/cloud/provider.go
- test/e2e/actions/deploy/deploy_operator.go
- test/int/datafederation_test.go
- test/int/deployment_test.go
> GCP and AWS improvements for test

- pkg/controller/validate/validate.go
- pkg/controller/validate/validate_test.go
- test/e2e/encryption_at_rest_test.go
> CLOUDP-167207: Validate GCP Service Account Key

- Makefile
- pkg/controller/atlas/client.go
- pkg/controller/atlas/client_test.go
- pkg/util/httputil/decoratedclient_test.go
- pkg/util/httputil/transportclient.go
> Support Atlas client transport customization

- go.mod
- go.sum
- pkg/controller/atlasproject/custom_roles.go
- pkg/controller/atlasproject/custom_roles_test.go
- pkg/controller/validate/validate.go
> Swap hashi mutlierror for native go implementation

- .github/actions/clean-vpc/azure.go
- .github/actions/clean-vpc/gcp.go
- .github/actions/clean-vpc/main.go
- .github/actions/cleanup-pe/cleanall.go
- .github/actions/cleanup-pe/main.go
- .github/actions/cleanup/deployment/advanced.go
- .github/actions/cleanup/deployment/datafederation.go
- .github/actions/cleanup/deployment/deployment.go
- .github/actions/cleanup/deployment/serverless.go
- .github/actions/cleanup/main.go
- .github/actions/cleanup/project/networkpeering.go
- .github/actions/cleanup/project/pe.go
- .github/actions/cleanup/project/project.go
- .github/workflows/cleanup-all.yml
Cleaner: continue on error for PE and peering connections
> Cleaner: continue on error for PE and peering connections

- pkg/controller/connectionsecret/connectionsecrets.go
- pkg/controller/connectionsecret/ensuresecret.go
- pkg/controller/connectionsecret/ensuresecret_test.go
Fixed missing private endpoint connection string for sharded clusters
> HELP-48316: Fixed missing private endpoint connection string for sharded clusters

- go.mod
- go.sum
- pkg/api/v1/status/cloud_provider_access.go
- pkg/controller/atlasproject/cloud_provider_access.go
- test/e2e/api/atlas/atlas.go
- test/e2e/encryption_at_rest_test.go
- test/e2e/integration_test.go
> CLOUDP-194441: Manually bump Atlas client to version 0.32

- cmd/manager/main.go
- go.mod
- go.sum
- pkg/api/v1/atlasdeployment_types.go
- pkg/controller/atlas/api_error.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
- pkg/controller/atlasdeployment/clusters_mock_test.go
- pkg/controller/atlasdeployment/serverless_mock_test.go
- pkg/controller/atlasproject/atlasproject_controller.go
- test/e2e/annotations_test.go
- test/int/databaseuser_protected_test.go
- test/int/deployment_protected_test.go
- test/int/deployment_test.go
- test/int/deployment_unprotected_test.go
- test/int/integration_suite_test.go
> CLOUDP-178750: Add deletion protection to deployments 

- go.mod
- go.sum
- pkg/controller/atlasproject/cloud_provider_access_test.go
- test/e2e/project_deletion_protection_test.go
> Fix CPA tests

- docs/testing.md
> CLOUDP-170078: Add testing guide

- cmd/manager/main.go
- pkg/api/v1/atlasdatafederation_types.go
- pkg/controller/atlas/api_error.go
- pkg/controller/atlasdatafederation/datafederation.go
- pkg/controller/atlasdatafederation/datafederation_controller.go
- test/int/datafederation_protect_test.go
- test/int/integration_suite_test.go
> CLOUDP-178754: Deletion Protection for Data Federation

- .github/workflows/test-forked.yml
Should avoid running forked tests when not expected, like here:
https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/5890991221?pr=1082
> Run forked test only on labeled PRs

- .github/workflows/cloud-tests-forked.yml
- .github/workflows/cloud-tests.yml
Turns out GitHub does not queue up requests. It only has a running and a pending slot.
With `cancel-in-progress: true` the latest request was jumping the queue and running instead of the ongoing test.
With `cancel-in-progress: true` the latest request will not kill the ongoing test, but will jump the queue on any other pending test that was already waiting there.
There seems to be [no change coming about this](https://github.com/orgs/community/discussions/5435#discussioncomment-2016448).
Seems a more approachable queueing, given GH limitations, is per user. So that at least each developer is in control of their test queue, we do not interfere with each other and still reduce test concurrency a tiny bit.
* ~~Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if …
> CLOUDP-194416: Use per user CI queues

- pkg/api/v1/custom_roles.go
- pkg/api/v1/custom_roles_test.go
- pkg/controller/atlasproject/custom_roles.go
- test/int/project_test.go
> CLOUDP-195522: Correctly fix custom role translation for Atlas API

- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/auditing.go
- pkg/controller/atlasproject/auditing_test.go
- pkg/controller/atlasproject/custom_roles.go
- pkg/controller/atlasproject/custom_roles_test.go
- pkg/controller/atlasproject/encryption_at_rest.go
- pkg/controller/atlasproject/encryption_at_rest_test.go
- pkg/controller/atlasproject/maintenancewindow.go
- pkg/controller/atlasproject/maintenancewindow_test.go
- pkg/controller/atlasproject/project_settings.go
- pkg/controller/atlasproject/project_settings_test.go
- pkg/controller/atlasproject/teams.go
- pkg/controller/atlasproject/teams_test.go
- test/e2e/project_deletion_protection_test.go
> CLOUDP-175080: Deletion protection for project resources (final)

- .github/workflows/release-post-merge.yml
Fixed no space left on the device error for the release process
> Fixed no space left on the device error

- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
- pkg/controller/atlasdeployment/serverless_deployment.go
- pkg/controller/atlasdeployment/serverless_private_endpoint.go
- pkg/controller/atlasdeployment/serverless_private_endpoint_mock_test.go
- pkg/controller/atlasdeployment/serverless_private_endpoint_test.go
- pkg/controller/workflow/result.go
- test/e2e/actions/project_flow.go
- test/e2e/configuration_test.go
- test/e2e/k8s/operator.go
- test/e2e/model/dataprovider.go
- test/e2e/private_link_test.go
- test/e2e/serverless_pe_test.go
* ~~Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).~~
* ~~Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.~~
> CLOUPD-193335: Deletion Protection Serverless Private Endpoints

- .github/workflows/paths-filter.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test-int.yml
- Dockerfile
Use Red Hat's Micro Universal Base Image, rather than Minimal. This cuts the compressed size (download from Dockerhub) from ~90mb to ~30mb, and the uncompressed (on disk) from ~260mb to ~77mb. 
This should also reduce security exposure through simply having less packages in the image; [micro has 20](https://catalog.redhat.com/software/containers/ubi9/ubi-micro/615bdf943f6014fa45ae1b58?container-tabs=packages) compared to [minimal's 102](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?container-tabs=packages).
> CLOUDP-196136: Use UBI micro base image instead of minimal

- .github/workflows/test-e2e-gov.yml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
- pkg/api/v1/atlascustomresource.go
- pkg/api/v1/atlasproject_types.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatafederation/datafederation_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/backup.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/project.go
- pkg/controller/atlasproject/team_reconciler.go
- pkg/controller/connectionsecret/connectionsecrets.go
- pkg/controller/customresource/customresource.go
- pkg/controller/customresource/customresource_test.go
- pkg/controller/validate/validate.go
- pkg/controller/validate/validate_test.go
- pkg/controller/workflow/reason.go
- test/e2e/api/atlas/atlas.go
- test/e2e/atlas_gov_test.go
- test/e2e/k8s/operator.go
> CLOUDP-199666: Support Atlas for government

- .github/workflows/cloud-tests-forked.yml
- .github/workflows/cloud-tests.yml
This makes the merge to `main` use their own unique queue for the expensive cloud tests. That way, they are not affecting by a developer trying to also build a PR while the merge is still ongoing. Note that merges still happen one at a time.
> CLOUDP-202685: Main branch merges in its own queue

- .github/workflows/rebuild-released-images.yaml
By default the schedules keep on working as before, on schedule calls `github.event.inputs.image_repo` is not set and therefore `IMAGE_REPOSITORY` is set to `"mongodb/mongodb-atlas-kubernetes-operator"`.
When invoked manually in a workflow dispatch, if the user does not change it, the default repo is set to the prereleases one  `"mongodb/mongodb-atlas-kubernetes-operator-prerelease"`. Still the releases repo is available to be selected, as needed.
> CLOUDP-179084: Enable dialy build testing

- .github/workflows/test.yml
- Tested that `cloud-tests` triggers [the expensive cloud tests: integration and e2e](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/6585982699/job/17893468648?pr=1184)
- Tested that removing the `cloud-tests` even with tests in progress, will skip the cloud tests.
> Run Cloud Test on  label

- .github/actions/build-push-image/action.yaml
- .github/workflows/rebuild-released-images.yaml
- .github/workflows/release-post-merge.yml
✅  [Create Release (test)](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/6574565626/job/17859870298)
✅  [E2E tests](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/6574580645)
✅  [Integration tests](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/6575123825)
The build-and-push sub-action will:
- **Fail** if both push to docker and quay are unset.
- Set the main build **tag** to push to Docker OR Quay.
- If both flags are set it means it pushed to docker and also must push to quay. If both were unset it would have already failed. If docker was unset then it would have already push to quay. If quay is unset, no need to push to quay.
- If the verified version (`*-certified`) is set AND push to quay is also set, push verified version to …
> CLOUDP-205248: Build once on release

- test/int/integration_suite_test.go
- test/int/project_test.go
This fix includes several race condition fixes on Kubernetes object deletion and update.
It also includes a few project renames on the Kubernetes side that seem to fix some flakiness. I believe some tests were interfering with each other on the same project test set.
> CLOUDP-212063: Fix k8s project delete and update race conditions

- tools/clean/atlas/atlas.go
- tools/clean/atlas/network_peering.go
- tools/clean/provider/gcp.go
Seems that `ListPeeringConnections` would render only AWS related peering by default.
Apart from that, GCP VPC removals could not be done before removing their subnets.
Fixing both here should probably fix the issues for GCP. For Azure we have not detected stuck entries so far.
> CLOUDP-212108: Fix net peering cleanups

- .github/workflows/release-post-merge.yml
- .gitignore
- Makefile
- scripts/release-helm.sh
- tools/makejwt/go.mod
- tools/makejwt/go.sum
- tools/makejwt/main.go
- tools/makejwt/main_test.go
Use New GH App AKO Releaser to kick off the helm chart release from this repo.
Created a new `makejwt` tool to create a JWT token from the GitHub App RSA key.
Overall process:
1. Build & test the Go tool `makejwt`.
1. Use the new `scripts/release-helm.sh` script to kick of the Helm charts release.
The `scripts/release-helm.sh` needs to do some curl dance to go from the RSA key to a successful REST API call:
1. Run the `makejwt` tool to obtain the **JWT** from the App RSA key.
1. Use the **JWT** to query the **Installation Id** of the helm-charts repo via REST.
1. Use the **JWT** and the **Installation Id** to query **access token** the via REST.
1. Use the **access token** and Version to kick off the helm release via REST.
Test:
✅  [Test to kick Helm Chart release using AKO release GitHub …
> CLOUDP-212564: Kick Helm Chart release using GitHub App

- .github/workflows/build-test-app.yml
This should avoid **dependabot** changes such as #1290 trying to run a push event which requires credential access that **dependabot** should not have and writing to a registry that it should not be doing.
> CLOUDP-218740: Only run test-app push test on main

- Makefile
This is support fix for old version 1.7.3 which turned out to be broken when we bumped Go to 1.20 in the `Dockerfile` but the `Makefile` was still depending on the container image libc version, via CGO being enabled.
This same fix is already included in version `1.8.0` BTW. Once this is merged to the `v1.7.3-branch` we will update the `v1.7.3` tag and rebuild that version to fix consumers.
> CLOUDP-220809: Fix v1.7.3 rebuilds

- .github/workflows/test-e2e.yml
- cmd/manager/main.go
- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- go.mod
- go.sum
- internal/featureflags/featureflag.go
- internal/featureflags/featureflag_test.go
- pkg/api/v1/atlasdatabaseuser_types.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- test/e2e/db_users_oidc.go
- test/e2e/db_users_test.go
- test/e2e/operator_type_wide_test.go
- test/helper/e2e/actions/deploy/deploy_operator.go
- test/helper/e2e/actions/project_flow.go
- test/helper/e2e/actions/steps.go
- test/helper/e2e/data/user.go
- test/helper/e2e/k8s/operator.go
- test/int/integration_suite_test.go
Added OIDC and AWS IAM auth fields for AtlasDatabaseUser
> CLOUDP-209691: Added OIDC and AWS IAM auth fields for AtlasDatabaseUser

- pkg/controller/atlas/provider_test.go
- pkg/controller/atlasproject/auditing_test.go
- pkg/controller/atlasproject/cloud_provider_integration_test.go
- pkg/controller/atlasproject/custom_roles_test.go
- pkg/controller/atlasproject/encryption_at_rest_test.go
- pkg/controller/atlasproject/integrations_test.go
- pkg/controller/atlasproject/ipaccess_list_test.go
- pkg/controller/atlasproject/maintenancewindow_test.go
- pkg/controller/atlasproject/network_peering_test.go
- pkg/controller/atlasproject/project_settings_test.go
- pkg/controller/atlasproject/team_reconciler_test.go
- pkg/controller/atlasproject/teams_test.go
- pkg/controller/watch/watched_resource_handler_test.go
- test/app/main.go
- test/e2e/project_deletion_protection_test.go
- test/int/backup_protected_test.go
- test/int/databaseuser_protected_test.go
- test/int/deployment_protected_test.go
- test/int/deployment_unprotected_test.go
- test/int/project_protect_test.go
We should use `context.Background()` everywhere. TODO() is only for cases where code is still work in progress:
https://pkg.go.dev/context#TODO
> Code should use context.TODO when it's unclear which Context to use or it is not yet available (because the surrounding function has not yet been extended to accept a Context parameter).
> CLOUDP-221636: Consolidate on context.Background

- .github/workflows/cloud-tests.yml
- .github/workflows/test-e2e-gov.yml
- .github/workflows/test.yml
The idea is to force ALL tests to run at merge time within the merge queue, which triggers with event [`merge_group`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group).
- The event `merge_group` triggers the overall `test.yml`.
- The event `merge_group` is sufficient to trigger cloud tests, run filters will not stop it.
- The `cloud-tests.yml` `Allowed` check is always true on `merge_group`.
- The `cloud-tests.yml` triggers the `e2e-test-gov.yml` only on `merge_group`.
- The `e2e-test-gov.yml` workflow is no longer self triggered by closed PR.
> CLOUDP-222442: Run all test in merge queue

- pkg/controller/atlasdeployment/advanced_deployment.go
- pkg/controller/atlasdeployment/advanced_deployment_test.go
- pkg/controller/atlasdeployment/region_configuration.go
- pkg/controller/atlasdeployment/region_configuration_test.go
- test/int/deployment_test.go
Atlas rejects updates with empty instance sizes with the following error:
> 400 (request "MISSING_ATTRIBUTE") The required attribute instanceSize was not specified.'
This forces us to select a value to be sent on updates even when we would want Atlas to ignore it and override it for us.
This fix does the following:
1. Instead of setting empty values when autoscaling is ON and something outside the region config was changed, the values from the Atlas side are set, when available and needed.
2. For comparing the region config or the cluster config we specifically ignore instance size differences between the Atlas status and the Kubernetes settings ONLY when autoscaling is ON for the region.
Unit tests have been modified to verify this new behavior.
> CLOUDP-226369: Fix instance size updates when auto-scale ON

- .github/actions/gen-install-scripts/entrypoint.sh
- .gitignore
- scripts/e2e_local.sh
- scripts/split_roles_yaml.sh
- test/helper/e2e/config/config.go
This change puts `e2e` testing support file on a separate directory so they do not stomp on tracked repo files for releases. That way, local runs of `e2e` tests should no longer create spurious changes that are not to be committed.
> Avoid e2e test changing tracked files

- .github/actions/gen-install-scripts/entrypoint.sh
- .gitignore
- scripts/e2e_local.sh
- scripts/split_roles_yaml.sh
- test/helper/e2e/config/config.go
This reverts commit 3128a79e90b7550e4e185a39c003d0739d6a45ff.
> Revert "Avoid e2e test changing tracked files (#1329)"

- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
- pkg/api/v1/atlasdeployment_types.go
- pkg/api/v1/atlasdeployment_types_test.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatafederation/datafederation_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/team_reconciler.go
- pkg/controller/customresource/customresource.go
- pkg/controller/customresource/customresource_test.go
- pkg/controller/customresource/protection.go
- pkg/controller/customresource/protection_test.go
- test/int/datafederation_test.go
- test/int/deployment_test.go
Added terminationProtection flag
> CLOUDP-224541: Added terminationProtection flag

- .github/workflows/release-post-merge.yml
The version is calculated at the `Print Env and Get version` step. Such version takes the input version as a hint, or calculates it from the push event branch name.
In either case, the version to use after that step is always `steps.tag.outputs.version`, **never** `github.event.inputs.version` again.
> CLOUDP-230403: Avoid error 'version' not provided

- .github/workflows/rebuild-released-images.yaml
- .github/workflows/release-post-merge.yml
- .gitignore
- Makefile
- scripts/sign-multiarch.sh
- scripts/sign.sh
- scripts/verify.sh
✅ [Sign and self verification test passed](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8003743939/job/21859696852)
Includes:
- Signing images for releases and rebuilds.
- Signing from Makefile rule.
- Script to detect multi architecture SHAs and sing the parent manifest and platform images.
- Script for each individual image signature.
Note the new secrets required and already populated in the CI `release` environment:
- Parameter `PKCS11_URI` required by Garasign
- Credentials for Garasign: `GRS_USERNAME` & `GRS_PASSWORD`
- Credentials for the MongoDB Artifactory holding the Garasign container `MDB_ARTIFACTORY_USERNAME` & `MDB_ARTIFACTORY_PASSWORD`
> CLOUDP-212054: Sign images with Garasign

- .github/workflows/cloud-tests.yml
- .github/workflows/test-e2e-gov.yml
Seems the blocked was a second if check that I had not noticed before testing: `if: github.event.pull_request.merged == true` Within the actual gov test workflow.
I have replaced it with the check we want, as it needs to happen for both `push` and `merge_group`. 
Note: The `merge_group` event not fire for now, but once we can enable the merge queue, it should start working right away without further changes, then we can probably remove the need to re-test at `push`.
This change also enables workflow_dispatch calls, so we can run it manually as needed.
> CLOUDP-231189: Make sure Gov tests run on push

- .github/workflows/test-e2e-gov.yml
Otherwise we [can try to trigger it manually](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/workflows/test-e2e-gov.yml), but [it gets skipped](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8016888440).
> CLOUDP-231189: Allow workflow_dispatch to run gov tests

- .github/workflows/test.yml
- .github/workflows/update-licenses.yml
✅ Managed to fix dependabot PR #1408 (launched manually)
> CLOUDP-231603: Fix updating dependabot licenses

- .github/workflows/update-licenses.yml
Hopping this will fix the bot access on this workflow:
https://github.com/ad-m/github-push-action/issues/96
> CLOUDP-231603: Add permissions on fix bot workflow

- config/crd/bases/atlas.mongodb.com_atlasbackuppolicies.yaml
- pkg/api/v1/atlasbackuppolicy_types.go
- test/e2e/backup_config_test.go
> CLOUDP-228985: Support yearly frequency/retention for backup policy

- .github/workflows/test.yml
Just avoid contributions to run ANY tests at all by default.
Instead, testing needs to be explicitly allowed by labelling the PR after inspecting it looks sane.
___
✅ [Test on fork: Dummy change from another fork had to be labeled to run tests](https://github.com/josvazg/mongodb-atlas-kubernetes/pull/27).
✅ [Test on fork: Dependabot change runs tests after adding the `retest` label, as usual](https://github.com/josvazg/mongodb-atlas-kubernetes/pull/26).
✅ [Test on fork: Regular change runs tests by default](https://github.com/josvazg/mongodb-atlas-kubernetes/pull/28).
> Do NOT use pull_request_target events

- .github/actions/certify-openshift-images/Dockerfile
- .github/actions/certify-openshift-images/entrypoint.sh
**Note:** preflight 1.9.1 requires `--platform` to be set, otherwise it errors:
```
Error: cannot process image manifest of different arch without platform override
```
This was verified locally using:
```bash
#!/bin/sh
set -eou pipefail
REPOSITORY=mongodb/mongodb-atlas-kubernetes-operator
VERSION=2.1.0
DIGESTS=$(docker manifest inspect "quay.io/${REPOSITORY}:${VERSION}" | jq -r '.manifests[] | select(.platform.os!="unknown") | .digest')
PLATFORMS=($(docker manifest inspect "quay.io/${REPOSITORY}:${VERSION}" | jq -r '.manifests[] | select(.platform.os!="unknown") | .platform.architecture'))
INDEX=0
for DIGEST in $DIGESTS; do
preflight check container "quay.io/${REPOSITORY}@${DIGEST}" \
--artifacts "${DIGEST}" \
--platform "${PLATFORMS[$INDEX]}"
let INDEX=${INDEX}+1
done
```
Output:
``` …
```
> CLOUDP-238190: certify-openshift-images/Dockerfile: bump preflight check version

- README.md
- config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- config/samples/atlas_v1_atlasbackuppolicy.yaml
- config/samples/atlas_v1_atlasbackupschedule.yaml
- config/samples/atlas_v1_atlasdatabaseuser.yaml
- config/samples/atlas_v1_atlasdeployment.yaml
- config/samples/atlas_v1_atlasproject.yaml
I replaced the hard-coded examples with references from inside our config sample folder. Ensuring both work
> CLOUDP-222191: Update quick start guide and provided samples

- test/int/federated_auth_test.go
> Update FedAuth test

- .github/workflows/test-e2e-gov.yml
- .github/workflows/test-e2e.yml
This might help with serverless-pe failures like this:
```
Ginkgo timed out waiting for all parallel procs to report back
```
> set ginkgo interceptor to none

- .github/workflows/release-post-merge.yml
> CLOUDP-238747: Fix automatic release on PR merge

- .github/workflows/rebuild-released-images.yaml
- .github/workflows/release-post-merge.yml
- scripts/verify.sh
Before merging this I would need to update the secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD`.
New username is [svcdockerhubatlaskubernetes202](https://hub.docker.com/u/svcdockerhubatlaskubernetes202)
Note those creds will be lost once we do the change. I have tested we can push to all 3 registries in use:
- [docker.io/mongodb/mongodb-atlas-kubernetes-operator](https://hub.docker.com/r/mongodb/mongodb-atlas-kubernetes-operator/tags)
- [docker.io/mongodb/mongodb-atlas-kubernetes-operator-prerelease](https://hub.docker.com/r/mongodb/mongodb-atlas-kubernetes-operator-prerelease/tags)
- [docker.io/mongodb/signatures](https://hub.docker.com/r/mongodb/signatures/tags)
Any other testing required needs to happen before we make the **credentials** change.
> CLOUDP-238743: Use mongodb/signatures

- config/manager/manager.yaml
> CLOUDP-239117: Increased resources limits for AKO container

- .github/workflows/test-int.yml
- test/int/deployment_test.go
> Update deployment sharding test

- .github/actions/gen-install-scripts/Dockerfile
- .github/workflows/openshift-upgrade-test.yaml
- .github/workflows/test-e2e.yml
- PROJECT
I'm anticipating this task once I'd like to have it to be able to ship some code with generics at https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1466
As I have been using operator-sdk in the latest version for a while locally, I checked what was necessary to migrate/update it and it seems to be as simple as this PR shows. No changes in base manifests.
The next release, bundle will reflect the update of controller gen in the manifests and the new project layout, `go.kubebuilder.io/v4` in the CSV:
The warning triggered was because `PROJECT` config had v1beta1 API set for backup CRDs (not sure why) but both CRDs were already in v1(along with all others) and didn't have changes in them.
> CLOUDP-238915: Move to operator-sdk v1.34.1

- .github/workflows/release-post-merge.yml
And do not release to GitHub on pre-releases.
This should avoid launching the "**Create Release**" workflow unless it is a release, pre-release or a manual invocation. Which should avoid noise here:
https://github.com/mongodb/mongodb-atlas-kubernetes/actions/workflows/release-post-merge.yml
> CLOUDP-238747: Act only on (pre)releases or manual launches

- Makefile
- scripts/sign-multiarch.sh
✅ [Build and sign tag 2.2.1-rc0](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8539965791/job/23395938488)
- Use the digest directly as the multi-arch image SHA to sign, rather than the inspected JSON ID. That ID does not always match the digest.
- Install cosign version 2 on the CI.
> CLOUDP-240887: Fix CI signatures

- pkg/api/v1/status/team.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/atlasproject_controller_test.go
- pkg/controller/atlasproject/teams.go
- pkg/controller/atlasproject/teams_test.go
- pkg/controller/workflow/reason.go
- test/e2e/teams_test.go
Ensure teams are always cleaned up
> CLOUDP-239182: Ensure teams are always cleaned up

- bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
This allows to test PR #1507 
Upon merging, the expectation is this will:
- Trigger the `tag.yml` upon closing the PR, creating a tag `v2.2.2-rc0` for a pre-release.
- And then call workflow `release-port-merge.yml` that should skip GitHub and Helm Chart & RedHat certified release, ad this is a pre-release.
- No errors should happen, specially signature steps should work fine.
> Test pre-release 2.2.2-rc0

- .github/workflows/release-post-merge.yml
- .github/workflows/tag.yml
Workflow calls use `inputs.arg` instead of `github.event.inputs.arg`.
Also simplified some names and added traces on outputs.
Tested on a separate fork.
> CLOUDP-246462: Fix passing arg to wf call

- pkg/controller/watch/resource_watcher.go
- pkg/controller/watch/resource_watcher_test.go
Fix the concurrent writes for the ResourceWatcher
> CLOUDP-244156: Fix the concurrent writes for the ResourceWatcher

- .github/workflows/cloud-tests-filter.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- Run nightly tests at midnight, Monday to Friday.
- Always run **cloud tests** for the nightly schedules and release branches, which name starts with `release/`.
- For nightly tests on main, run the nightly Kubernetes test matrix (complete).
- Nightly run oldest and newest supported Kubernetes versions.
> CLOUDP-242965: Setup nightly tests on oldest and newest Kubernetes

- test/e2e/e2e_suite_test.go
- test/helper/e2e/config/config.go
Moving the creds file to the `output/` folder stops it from showing up as "untracked" by git and also prevents it from being checked in by mistake.
> CLOUDP-244541: Avoid GCE creds file leftover

- test/e2e/private_link_test.go
- test/helper/e2e/actions/cloud/gcp.go
- test/helper/e2e/actions/cloud/gcp_test.go
- test/helper/e2e/actions/cloud/provider.go
Change the method to get a GCP IP address into one that retries up to 7 times if the IP address selected randomly is already in use.
Added a test that verified the error message was coming from `createVirtualAddress`. Also added partial context passing to the GCP method.
> CLOUDP-243996: Fix GCP privatelink e2e IP conflict flakiness

- .github/workflows/cloud-tests-filter.yml
- .github/workflows/test-e2e.yml
Fix the computation of the test matrix for **scheduled** events.
Looking at [this example from today's schedule](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8776607163/job/24080359511):
```
GH_REF: refs/heads/main
GH_HEAD_REF: 
```
The value `github.head_ref` (**GH_HEAD_REF**) is not set on a scheduled event, but `github.ref` (**GH_REF**) is set as `refs/heads/main`. This change takes that into account to fix the comparison to be triggered correctly on scheduled test runs.
> CLOUDP-242965: Name matrix compute step

- .github/workflows/lint.yaml
- Makefile
- scripts/vulncheck.sh
- vuln-ignore
Selectively ignoring vulnerabilities.
The check is relatively cheap and makes more sense to do as early as possible. Developers are responsible for sending PRs that either pass the check or add ignored vulnerabilities to the list if they cannot be solved right away.
The script `scripts/vulncheck.sh` runs **govulncheck** removing all explicitly ignored vulnerabilities. It fails only any vulnerabilities are found after filtering the ignored ones.
The `vuln-ignore` file is expected to contain vulnerabilities using a pair of lines each in the following format:
```
GO-xxxx-yyyy
```
- Lines starting with `"##"` will be ignored, they are self documentation.
- Lines starting with `"# "` can be used for the SDLC checklist reporting the ignored vulnerabilities on a release.
- The rest of non empty …
> CLOUDP-245131: Run govulncheck at lint time

- test/helper/e2e/actions/cloud/gcp_test.go
Subnet 2 in GCP must be within the `10.0.0.128` range.
> Fix test to use correct sample IP

- pkg/api/v1/status/atlasdeployment.go
- pkg/controller/atlasdeployment/searchindexes.go
- pkg/controller/atlasdeployment/searchindexes_test.go
Fix: Remove all search index status entries where ID is empty
> CLOUDP-221979: Fix: Remove all search index status entries where ID is empty

- .github/actions/certify-openshift-images/Dockerfile
The `preflight-tool` is outdated. Bumping up to v1.9.2:
```
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.9.1' is not supported. Supported versions are: ['1.9.2', '1.9.4']", "status": 400, "trace_id": "0xa1aabed1b8c70960041f62de7632cfb4"} 2024/05/08 17:46:34 could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.9.1' is not supported. Supported versions are: ['1.9.2', '1.9.4']", "status": 400, "trace_id": …
```
> Bump up preflight tool version to 1.9.2

- Makefile
- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- pkg/api/v1/atlasdatabaseuser_types.go
> CLOUDP-248533: Fix X509Type as a enum

- cmd/manager/main.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
- pkg/controller/atlassearchindexconfig/atlassearchindexconfig_controller.go
- pkg/controller/atlassearchindexconfig/atlassearchindexconfig_controller_test.go
- pkg/controller/atlasstream/atlasstream_connection_controller.go
- pkg/controller/atlasstream/atlasstream_connection_controller_test.go
- pkg/controller/atlasstream/atlasstream_instance_controller.go
- pkg/controller/atlasstream/atlasstream_instance_controller_test.go
- pkg/indexer/atlassearchindexconfigs.go
- pkg/indexer/atlassearchindexconfigs_test.go
- pkg/indexer/atlasstreamconnections.go
- pkg/indexer/atlasstreamconnections_test.go
- pkg/indexer/atlasstreaminstances.go
- pkg/indexer/atlasstreaminstances_test.go
- pkg/indexer/indexer.go
- test/helper/e2e/k8s/operator.go
- test/int/integration_suite_test.go
This is a proposal to centralise indexing logic.
Currently, indexers are loosely coupled, mostly based on the fact that controller-runtime does not provider any abstraction for it. This PR introduces a lightweight interface `Indexer` which is being used for global registration and client-go mocks.
> [skunkworks] centralize indexers

- internal/pointer/pointer.go
New SDK empty fields are expected to be nullified in the JSON data. Using just `pointer.MakePtr()` will just make those fields pointers to an empty string, which the API interprets as NOT empty.
This fix has been proven necessary by PoC at #1543 to avoid such confusion with the API.
> Support empty fields for new SDK

- pkg/api/v1/common/common.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/backup.go
- pkg/indexer/atlasbackupschedules.go
- pkg/indexer/atlasbackupschedules_test.go
- pkg/indexer/indexer.go
This is a first iteration on converting existing resource watcher implementations in favour of indexers.
Here, we are converting backup schedules to trigger events on deployments via indexers rather than via the deprecated resource watcher.
> CLOUDP-244166: [skunkworks] refactor backup schedules to use indexers

- cmd/manager/main.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
- pkg/controller/atlasdeployment/backup.go
- pkg/indexer/atlasbackuppolicies.go
- pkg/indexer/atlasbackuppolicies_test.go
- pkg/indexer/atlasbackupschedules.go
- pkg/indexer/atlasbackupschedules_test.go
- pkg/indexer/atlassearchindexconfigs.go
- pkg/indexer/atlasstreamconnections.go
- pkg/indexer/atlasstreaminstances.go
- pkg/indexer/indexer.go
- test/helper/e2e/k8s/operator.go
- test/int/clusterwide/integration_suite_test.go
- test/int/integration_suite_test.go
This completely removes the resource watcher from the deployment controller.
> CLOUDP-244166: [skunkworks] backup policies indexer

- .github/actions/gen-install-scripts/action.yml
- .gitignore
- Makefile
- output/keep-directory.txt
- test/e2e/helm_chart_test.go
- test/helper/e2e/actions/steps.go
- test/helper/e2e/config/config.go
- test/helper/e2e/k8s/k8s.go
- test/helper/e2e/k8s/pod_logs.go
TL;DR:
- Make e2e clear rule also restore the helm chart repo.
- Move some generated e2e tests to properly `.gitgnored` paths.
Context:
When running locally, e2e tests will leave some git tracked files modified or create new files on non git-ignored paths.
This is counter-ergonomic and even dangerous. I have been saved from uploading secrets to GitHub by the GitHub secret hook more than once, when I inadvertently included e2e generated files in my PR changes.
This change does not fix the root cause but is part of a series to incrementally fix the issue, which has several components.Because `e2e tests` are:
- Generally not well behaved in where they generate files, they tend to leave them directly in the test dir at `test/e2e` or on some other directory that is not part of any path defined …
> Have better hygiene of e2e leftovers

- Makefile
Using `make run RUN_YAML=my-k8s-ako-sample-here.yml` you get:
- A local kind cluster to run...
- A freshly compiled manager with latest changes in the current terminal process.
- The `RUN_YAML` file applied after the CRDs are installed and the manager is started, so it will try to enforce the given state.
No need for ad-hoc scripts to get the same.
It relies on:
- `make install-crds` to install the latest versions of the CRDs.
- `make install-credentials` to create the root Atlas Operator credentials secret off your `MCLI_` env vars. *Remember to have those setup in advance in your terminal*.
- The `set-namespace` rule ensures the namespace set by `$(OPERATOR_NAMESPACE)` is in place.
If `RUN_YAML` is not passed in, `make run` will only launch the manager binary without any initial …
> Make run eases local interactive tests

- docs/dev/ci.md
> CLOUDP-212059: Add note about linters

- test/e2e/alert_config_test.go
- test/helper/e2e/k8s/operator.go
Most `e2e` tests configure one manager instance per test table case. There is no clean up between tests and, even if there was, that would be problematic with concurrent execution.
But the end of the matter is that `SetupSignalHandler` is designed to be called only once per binary:
```go
func SetupSignalHandler() context.Context {
close(onlyOneSignalHandler) // panics when called twice
```
So this change fixes some locally reproduced panics with the `alert_config_test.go`.
The fix is basically ensure all manager will share the same context source for canceling.
Related to CLOUDP-244907
---
> CLOUDP-244907: Fix e2e signal handler sharing

- Makefile
Now `make test-all-in-one` will just try out `deploy/all-in-one.yaml`. This should be run on the release branch before approval at least while this test is not yet automated.
Piggy backs on `make run` for getting their credentials.
---
```go
% make test-all-in-one                             
...
deployment.apps/mongodb-atlas-operator configured
```
---
> Test all-in-one.yaml from make

- Makefile
- scripts/upload-to-silk.sh
Adds `make upload-sbom-to-silk SBOM_JSON_FILE=...json` to upload SBOM lite files to Silk.
---
```
% make upload-sbom-to-silk SBOM_JSON_FILE=docs/releases/v2.2.2/linux-arm64.sbom.json   
...
Login Succeeded
...
docs/releases/v2.2.2/linux-arm64.sbom.json uploaded to Silk
```
---
> CLOUDP-239190: Upload SBOM lite files to Silk

- test/e2e/teams_test.go
The `teams` `e2e` test was frequently flaky. We also noticed it probably had isolation issues, as it tended to fail consistently if another `teams` test was running concurrently, like it happens on nightlies.
This fix managed to get a couple of concurrent teams test to succeed by using separate team test names. Note teams are  resources at the org level, so projects might fight each other when not using unique names.
This might not be the only source of flakiness in this test, but this PR seems a good first step.
> Fix teams e2e test isolation

- test/int/atlas_streams_test.go
> CLOUDP-246611: wire context in streams processing integration test

- pkg/controller/atlasdeployment/advanced_deployment.go
- pkg/controller/atlasdeployment/advanced_deployment_test.go
Bug from help ticket. This occurs in 2.1 (as reported) and in 2.3/main. This fix just sorts the slices present in the advanced deployment spec to avoid the diff mistakenly finding differences and repeatedly reconciling, spamming PATCH requests to Atlas every ~10s that had no effect.
Replication spec's Zone Name and Region config's Region Name must be unique, so we are safe to sort by them.
> CLOUDP-251760: Sort regionConfigs to avoid bad diffs

- .github/workflows/test-e2e.yml
- cmd/manager/main.go
- pkg/controller/controller.go
- test/e2e/cache_watch_test.go
- test/e2e/db_users_oidc_test.go
- test/e2e/db_users_test.go
- test/helper/e2e/actions/deploy/deploy_operator.go
- test/helper/e2e/actions/project_flow.go
- test/helper/e2e/k8s/k8s.go
- test/helper/e2e/k8s/operator.go
This is a bugfix for namespace watching filtering setup in both `main` and the `e2e` tests. The bug was discovered by issue #1515. The mistake came to be a mixture of controller runtime changing the manager setup and the operator code having a special case for watching a single namespace.
The fix consists of:
1. A new set of tests that detect the issue:
- Test the cache gets, list and reconciles to access 3 namespaces when:
- No namespaces were configured, meaning all 3 namespaces are accessible.
- One namespace was configured, meaning only that namespace is accessible.
- Two namespaces were configured, meaning two are accesible and the other is not.
2. The actual fix in `main` and `e2e` code:
- Do not treat the single namespace as a special case.
- Do not even get a "default namespace" …
> CLOUDP-250918: Add test to reproduce issue #1515

- docs/dev/ci.md
> Update CI doc to explicitly mention gosec

- docs/releases/v2.3.0/linux_amd64.sbom.json
- docs/releases/v2.3.0/linux_arm64.sbom.json
- docs/releases/v2.3.0/sdlc-compliance.md
- scripts/generate_upload_sbom.sh
This fixes a bug in the SBOM generation when the host machine does not match the arch from the `docker sbom` requested. Eg:
`image has unexpected architecture "arm64", which differs from the user specified architecture "amd64"`
The only workaround I found was to be explicit about the platform image SHA, so it will not complain and just compute the SBOM properly.
This PR also fixed version 2.3.0 SBOMs affected by this issue earlier.
> CLOUDP-251873: Fix 2.3.0 SBOMs and generation script

- .github/workflows/release-branch.yml
- .github/workflows/release-post-merge.yml
- Makefile
- docs/dev/image-sboms.md
- docs/dev/release.md
- docs/releases/sdlc-compliance.template.md
- scripts/gen-sdlc-checklist.sh
- scripts/generate_upload_sbom.sh
This PR solves several things:
- Decouples the creation of the SSDLC checklist document from the SBOMs that will be attached later, once the released image is actually available.
- The SSDLC checklist document creation is automated by the `release-branch.yml`workflow.
- The images SBOM creation is automated by a new branch and PR creation at the end of the `release-post-merge.yml`, right after the release images have been created.
- Both actions are also separated in the `Makefile` invocation.
- The script `scripts/gen-sdlc-checklist.sh` no longers invokes the SBOM creation.
- An specific development documentation is added to explain how the CI generates the SBOMs and how to create them manually.
- The SSDLC tamplet no longer links to the SBOMs directly, but just to the folder.
- It also …
> CLOUDP-251873: Decouple SBOMs from checklist

- pkg/api/v1/atlascustomresource.go
- pkg/api/v1/atlascustomresource_test.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatafederation/datafederation_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
- pkg/controller/atlasfederatedauth/atlasfederated_auth_controller.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/atlasproject/team_reconciler.go
- pkg/controller/atlasproject/teams.go
- pkg/controller/customresource/customresource.go
`MarkReconciliationStarted` is broken because it executes an update on conditions, setting `Ready=False` at the start of each reconciliation method. At the end of each reconcile method, `Get` and subsequent `Update` can cause an endless loop if local informer caches don't keep up. 
This fixes it by replacing it with an `InitCondition` method which initialises `Ready=False` on the in-memory reconciled object only, leaving persisting the final status update in place.
> CLOUDP-246312: [skunkworks] remove MarkReconciliationStarted

- config/crd/bases/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- config/crd/bases/atlas.mongodb.com_atlasbackuppolicies.yaml
- config/crd/bases/atlas.mongodb.com_atlasbackupschedules.yaml
- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- config/crd/bases/atlas.mongodb.com_atlasdatafederations.yaml
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasfederatedauths.yaml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
- config/crd/bases/atlas.mongodb.com_atlassearchindexconfigs.yaml
- config/crd/bases/atlas.mongodb.com_atlasstreamconnections.yaml
- config/crd/bases/atlas.mongodb.com_atlasstreaminstances.yaml
- config/crd/bases/atlas.mongodb.com_atlasteams.yaml
- pkg/api/v1/atlasbackupcompliancepolicy_types.go
- pkg/api/v1/atlasbackuppolicy_types.go
- pkg/api/v1/atlasbackupschedule_types.go
- pkg/api/v1/atlasdatabaseuser_types.go
- pkg/api/v1/atlasdatafederation_types.go
- pkg/api/v1/atlasdeployment_types.go
- pkg/api/v1/atlasfederatedauth_types.go
- pkg/api/v1/atlasproject_types.go
- pkg/api/v1/atlassearchindexconfig_types.go
- pkg/api/v1/atlasstreamconnection_types.go
- pkg/api/v1/atlasstreaminstance_types.go
- pkg/api/v1/atlasteam_types.go
This adds a `kubectl get atlas` to be able to retrieve all atlas resources:
```
$ kubectl get atlas -A
NAMESPACE   NAME                                            AGE
ns-search   atlasdeployment.atlas.mongodb.com/search-test   9s
NAMESPACE   NAME                                        NAME
ns-search   atlasproject.atlas.mongodb.com/my-project   atlas-search-test
NAMESPACE   NAME                                                                       AGE
ns-search   atlassearchindexconfig.atlas.mongodb.com/test-search-index-config          8s
ns-search   atlassearchindexconfig.atlas.mongodb.com/test-search-index-config-simple   8s
```
Additionally, this introduces short names for our CRDs:
```
NAME                              SHORTNAMES
atlasbackuppolicies               abp …
```
> CLOUDP-251999: [skunkworks] add "atlas" CRD category and short names

- cmd/manager/main.go
> CLOUDP-251770: Added zap-logging to the controller-runtime leader election.

- Makefile
- internal/mocks/atlas/integrations.go
- pkg/controller/atlasproject/integrations.go
- pkg/controller/atlasproject/integrations_test.go
> CLOUDP-260438: Fix redacted integration comparisons

- .github/workflows/openshift-upgrade-test.yaml
- scripts/openshift-upgrade-test.sh
https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/9970869505/job/27550963780
```
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.10+a2c84a5
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.15.19   True        False         12d     Cluster version is 4.15.19
```
> CLOUDP-260750: Display OpenShift cluster version

- scripts/e2e_local.sh
This allows to set your env MCLI env vars to the gov environment and the script will use those instead of the `.actrc` fallbacks.
> Allow to easily debug gov tests

- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasproject/atlasproject_controller.go
- pkg/controller/watch/predicates.go
- test/int/integration_suite_test.go
- test/int/syncperiod_test.go
> CLOUDP-261715: Enabled resync for Atlas custom resources

- pkg/api/v1/privateendpoint.go
- pkg/controller/atlasproject/private_endpoint.go
Refactor
I only found this usage that made sense to fix.
All other pointer usages are on admin types from the SDK which we do not own, and wrapping them on local types for this seems like an overkill.
> CLOUDP-242585: Fix getter to avoid pointer conversion

- .github/workflows/tag.yml
Before creating the SBOMs PR.
Otherwise the job fails as the release image is not ready to compute the per platform SBOMs.
> CLOUDP-264908: Wait for release image

- .github/workflows/test.yml
Should fix this error:
https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/10199327240
```
[Invalid workflow file: .github/workflows/update-licenses.yml#L56](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/10199327240/workflow)
error parsing called workflow
".github/workflows/update-licenses.yml"
-> "./.github/workflows/test.yml" (source branch with sha:de17e17780e38a27ffa4a527cccf15e8cb283e25)
: workflow is not reusable as it is missing a `on.workflow_call` trigger
```
> Allow workflow call from update licenses

- .github/workflows/test.yml
- .github/workflows/update-licenses.yml
The directly kicked off tests:
- Are not executed within the actual open PR, but on a separate action, disconnected.
- Are run on the original commit, not the one the update licenses fixed, so they fail anyways.
We might need to kick them indirectly, maybe labelling would work? Not sure.
> Revert attempted test fixes

- .github/workflows/update-licenses.yml
This is a quick experiment checking is this will fix our `dependabot` automated workflow after the licenses get fixed.
> Auto add retest label after updating licenses

- .github/workflows/update-licenses.yml
`AKObot` updates licenses at `dependabot` PRs. But after pushing its fix commit, the checks are not run, they need to be kicked manually.
Have tried several ways so try to automate them and none have worked:
- Changing labels manually works, but if done from a workflow, they do nothing.
- Closing and opening the PR manually re-run checks, but if done in a workflow it does nothing.
- Using a PAT to commit the changes with actions permissions also does not work.
This PR restores the update licenses workflow to its original state. We need to keep on adding `retest` label manually to run the `dependabot` PR tests to completion, one by one.
> Abort attempt to automate checks after AKObot

- internal/translation/dbuser/dbuser.go
- internal/translation/dbuser/dbuser_test.go
- pkg/controller/atlas/api_error.go
**What and why?**
There's an inconsistency in error codes: "USERNAME_NOT_FOUND" when fetching a user versus "USER_NOT_FOUND" when deleting. This discrepancy causes the operator to error, preventing the removal of the finalizer and blocking resource deletion.
> CLOUDP-265413: Operator failed to reconcile and already deleted user

- Makefile
The `make manager`target which was called before the `make image` target was building the image for the system that was called on instead of linux, which the dockerfile needs.
> [BUG] Fix for the makefile 'make image' target.

- .github/workflows/update-licenses.yml
After requesting extra permissions for our [GitHub App ako releaser](https://github.com/apps/ako-releaser/installations/44334998) with this [Zendesk ticket](https://help-it.mongodb.com/hc/en-us/requests/437709) this change should make the AKO bot updating licenses to auto label the PR with retest, so it will complete the unit tests without our manual intervention.
✅ [Manual workflow is able to set the `retest` tag on its own](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/10507336462)
> Add label retest after licenses update

- Makefile
- scripts/e2e_local.sh
- scripts/int_local.sh
- Fix `e2e` local script errors.
- Fix `int` local script for consistency to also prefer MCLI en vars of arcrc configs. Also remove redundant code in Makefile about this.
> CLOUDP-270164: Fix local tests scripts

- .github/workflows/update-licenses.yml
Small change to https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1780, which would attempt to add the retest label (to run tests again) even if it was already there, which would not run the tests. We now remove it beforehand, to ensure that the tests are run.
I have tested locally and attempting to remove a label that does not exist is fine (exit code 0), so this should not affect fresh PRs.
> Fix license update re-adding retest label

- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller_test.go
- pkg/controller/atlasdatabaseuser/databaseuser.go
- pkg/controller/atlasdatabaseuser/databaseuser_test.go
- test/e2e/db_users_oidc_test.go
- test/int/deployment_test.go
Should go after #1782 and before the actual addition of the custom ID for managing the Database Users on their own.
This is part of the series of changes drafted by #1769
> CLOUDP-266544: Refactor Database User state machine

- .github/workflows/test-e2e.yml
- test/e2e/datafederation_pe_test.go
- test/helper/e2e/actions/cloud/aws.go
The data federation e2e test is both broken and disabled.
This fixes it.
> CLOUDP-271519: Fix data federation e2e test and enable it again

- test/e2e/datafederation_pe_test.go
- test/helper/e2e/actions/cloud/aws.go
Instead of reverting https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1807 this PR tries to unflake the data federation e2e test by creating a dedicated VPC.
In addition it adds logic to wait for the deletion of VPC endpoints.
> CLOUDP-271519: test/e2e: use dedicated VPC for datafederation and wait for VPC deletion

- pkg/api/condition.go
- pkg/controller/atlasproject/project_test.go
- pkg/controller/atlasproject/teams.go
- pkg/controller/atlasproject/teams_test.go
- test/e2e/atlas_gov_test.go
- test/e2e/teams_test.go
> CLOUDP-273419: Don't delete teams when not assigned to a project

- .github/workflows/devbox-update.yml
Fixed the PR creating using [gh](https://cli.github.com/), which is available by default in GitHub workflow images.
✅ [Manual tests](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/11127955491/job/30921514716) created [PR #1849](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1846)
> CLOUDP-275610: Fix devbox updates

- .github/workflows/cleanup-all.yml
- .github/workflows/cleanup-gov-test.yml
- .github/workflows/cleanup-test.yml
- .github/workflows/openshift-upgrade-test.yaml
- .github/workflows/release-openshift.yaml
- .github/workflows/test-contract.yml
- .github/workflows/test-e2e-gov.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test-int.yml
There are now 4 separated credentials environments:
- `test` for test credentials which need to access Atlas QA and cloud envs.
- `gov-test` for test credentials on Atlas QA Gov and cloud envs.
- `openshift-test` for test credentials on the team Openshift cluster with access to quay.io images.
- `release` for release credentials to sign and publish Operator releases.
Changes:
- Cleanup split into **cleanup-test** and **cleanup-gov-test** with different set of credentials and scheduled. Cleanup all can still can both.
- Rest of workflow jobs have been constrained to their respective environments.
---
✅ [Test daily build to test release creds](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/11139819534/job/30957272977)
Cloud tests already exercise **test**, **gov-test** and …
> CLOUDP-237043: Use separated secret envs

- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller_test.go
- pkg/controller/workflow/result.go
> CLOUDP-277700: Reduced reconcile period for externally linked resources

- Makefile
Avoids version error such as:
"version of the resource $Resource is higher than the operator version $VERSION"
> CLOUDP-277877: Use NEXT_VERSION on make runs

- pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- pkg/controller/atlasdeployment/atlasdeployment_controller.go
- pkg/indexer/localcredentials.go
- pkg/indexer/localcredentials_test.go
- 1st commit adds a test to detect the race condition.
- 2nd commit fixes the race condition by using a function that generates the empty list for each call, instead of reusing the same value for all calls.
> CLOUDP-279474: Use generator to avoid sharing list value

- pkg/controller/atlasdatafederation/datafederation_controller.go
- pkg/controller/atlasdatafederation/datafederation_controller_test.go
- pkg/indexer/atlasdatafederationprojects.go
- pkg/indexer/atlasdatafederationprojects_test.go
- pkg/indexer/indexer.go
Currently, the Atlas Data Federation controller does not watch AtlasProject resources. This fixes it.
Note: this builds on top of https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1835
> CLOUDP-261995: watch for AtlasProject resources in AtlasDataFederation controller

- pkg/controller/atlasproject/integrations.go
- pkg/controller/atlasproject/integrations_test.go
Atlas redacts integrations secrets for security reasons, which means we cannot:
- Compare them to check whether they need to be re-applied or not.
- Detect whether or not applied secrets got properly set.
This change preserves that behaviour without assuming any extension to this behaviour coming any time soon. A proper fix will have to come from Atlas, for instance, sending a hash of the secret that allows comparison by applying the same on the client side.
> CLOUDP-280225: Refactor integration secret checks

- .github/workflows/release-post-merge.yml
- .github/workflows/tag.yml
With `Automatically delete head branches` ON we no longer accumulate merged branches, but the tag workflow broke, because the merged branch was deleted before the workflow could tag it.
This fix:
1. Tags the just merged `main` branch instead of the removed merged branch.
2. Allows to call tag manually, in which case the branch to tag for release is an input parameter defaulting to `main`.
3. The SBOM PR in triggered by the release workflow completion. The version is taken as an output from the release.
> CLOUDP-281207: Tag main on release merge

- internal/translation/datafederation/conversion_endpoints.go
- internal/translation/datafederation/conversion_endpoints_test.go
- pkg/controller/atlasdatafederation/datafederation_controller.go
- pkg/controller/atlasdatafederation/private_endpoint.go
- pkg/controller/atlasdatafederation/private_endpoint_test.go
- test/e2e/datafederation_pe_test.go
This is an alternative to #1928 and introduces a state machine handling.
It also prevents accidental deletion of data federation private endpoints that are not tracked by AKO.
> CLOUDP-283049: fix data federation endpoint reconciliation

- test/helper/e2e/k8s/k8s.go
This initialises the Kubernetes schemas only once in tests, so that race conditions won't happen. Just like in production.
> CLOUDP-285690: Fix race condition between schema and events

- internal/set/identifiable.go
- internal/set/identifiable_test.go
- pkg/api/v1/atlasdatafederation_types.go
- pkg/api/v1/atlasteam_types.go
- pkg/api/v1/project/integration.go
- pkg/api/v1/project/ipaccesslist.go
- pkg/api/v1/status/privateendpoint.go
- pkg/controller/atlasproject/cloud_provider_integration.go
- pkg/controller/atlasproject/integrations.go
- pkg/controller/atlasproject/integrations_test.go
- pkg/controller/atlasproject/private_endpoint.go
We want to deprecate the "Identifiable" interface in lieu of the translation layer. It's current construct is too brittle and can cause subtle issues when comparing types, potentially leading to wrong implementations.
> CLOUDP-288535: deprecate Identifiable and remove unused implementations

- config/crd/bases/atlas.mongodb.com_atlasprivateendpoints.yaml
- pkg/api/v1/atlasprivateendpoint_types.go
Changes CRD shortname for private endpoint from `pe` to `ape` to stay inline with convention of starting atlas resource shortnames with 'a'. Relevant manifests have been regenerated.
Connected ticket: [CLOUDP-289101](https://jira.mongodb.org/browse/CLOUDP-289101)
> CLOUDP-289101: Changes CRD shortname for private endpoint

- pkg/controller/atlasproject/custom_roles.go
- pkg/controller/atlasproject/custom_roles_test.go
> CLOUDP-268810: CustomRoles: remove only those previously configured in AKO

- api/v1/atlascustomrole_types.go
- internal/controller/atlasproject/custom_roles.go
- internal/controller/atlasproject/custom_roles_test.go
This fixes resolves: https://github.com/mongodb/mongodb-atlas-kubernetes/issues/2015
> CLOUDP-293113: Fixed unintended removals of custom roles

- .github/actions/gen-install-scripts/entrypoint.sh
- Makefile
- config/crd/bases/atlas.mongodb.com_atlascustomroles.yaml
- scripts/deploy.sh
> CLOUDP-293822: Fix targets affected by new project layout

- internal/controller/atlas/provider.go
- internal/controller/atlas/provider_test.go
- internal/controller/atlasbackupcompliancepolicy/atlasbackupcompliancepolicy_controller.go
- internal/controller/atlascustomrole/atlascustomrole_controller.go
- internal/controller/atlascustomrole/atlascustomrole_controller_test.go
- internal/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- internal/controller/atlasdatafederation/datafederation_controller.go
- internal/controller/atlasdeployment/atlasdeployment_controller.go
- internal/controller/atlasdeployment/atlasdeployment_controller_test.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller_test.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller_test.go
- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlasproject/atlasproject_controller_test.go
- internal/controller/atlasproject/team_reconciler.go
- internal/controller/atlasproject/teams.go
- internal/controller/atlasproject/teams_test.go
- internal/controller/atlassearchindexconfig/atlassearchindexconfig_controller.go
- internal/controller/atlasstream/atlasstream_connection_controller.go
- internal/controller/atlasstream/atlasstream_instance_controller.go
- internal/controller/atlasstream/atlasstream_instance_controller_test.go
- internal/controller/workflow/context.go
- internal/dryrun/context.go
- internal/dryrun/error.go
- internal/dryrun/transport.go
- internal/dryrun/transport_test.go
- internal/httputil/loggedclient.go
- internal/operator/builder.go
This adds a dry run transport towards Atlas calls. Note that this contribution is a no-op for now. The operator starts in non-dry-run mode.
> CLOUDP-280012: Add http dry run transport for Atlas

- test/helper/contract/contract.go
Add support for contract tests focus, so you can run only one contract test at a time.
> Support focus on contract tests

- api/v1/atlasdatabaseuser_types_test.go
- api/v1/atlasdeployment_types_test.go
- api/v1/atlasprivateendpoint_types_test.go
- api/v1/project_reference_cel_test.go
Avoid repeating the same 8 test cases again and again on each new CRD type using the CEL validations for dual project references.
> CLOUDP-280230: Simplify and avoid CEL validation repetitions

- test/contract/audit/audit_test.go
- test/contract/ipaccesslist/ipaccesslist_test.go
We should use random project names in contract tests to avoid conflicts.
> CLOUDP-294831: Use random project names on contract tests

- .github/actions/certify-openshift-images/entrypoint.sh
While investigating why tags are not synced in the RedHat catalogue I found that our certification is actually broken and prevents proper certified images to be displayed at https://catalog.redhat.com/software/container-stacks/detail/606c2c5a7c9ac7d8cc203e51.
While discussing with RedHat support I found that our preflight certification script must be changed to certify the whole manifest image rather than the individual platform images.
This fixes it.
**Proof of work**: I executed the E2E test pointing to commit https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2047/commits/68409dbb39539754f69b38f5a3e6ed3718ee7c43:
It yielded the following successful result, see https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/12786281981/job/35643041420:
``` …
```
> CLOUDP-294849: preflight: check manifest image only

- .github/actions/certify-openshift-images/Dockerfile
This uses the latest version of the RedHat preflight tool for certification.
**Proof of work**: Started E2E tests pointing to this PR:
Github Action https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/12786964036/job/35645145199 yielded the following result using the latest version of `preflight` (1.11.1):
```
Check and Submit result to RedHat Connect
time="2025-01-15T11:09:01Z" level=info msg="certification library version" version="1.11.1 <commit: f787b66d23c7c29f078c43e2c2f23d32f4c6310e>"
...
```
> CLOUDP-288315: certify-openshift-images: use latest version of preflight

- test/helper/contract/contract.go
- test/helper/contract/skip_test.go
Fix bug skipping all contract tests by default and add unit tests to verify fix.
> CLOUDP-294932:  Fix contract test skips

- internal/indexer/indexer.go
controller-runtime's `Manager` satisfies the `Cluster` (https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.20.0/pkg/cluster#Cluster) interface.
We are going to need the `Cluster` primitive for dry-run functionality and need to register indexers for this use case. This changes the signature to accept `Cluster` for indexer registration.
> CLOUDP-293806: indexer: use cluster rather than manager

- internal/controller/atlasbackupcompliancepolicy/atlasbackupcompliancepolicy_controller.go
- internal/controller/atlascustomrole/atlascustomrole_controller.go
- internal/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- internal/controller/atlasdatafederation/datafederation_controller.go
- internal/controller/atlasdeployment/atlasdeployment_controller.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller.go
- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlassearchindexconfig/atlassearchindexconfig_controller.go
- internal/controller/atlasstream/atlasstream_connection_controller.go
- internal/controller/atlasstream/atlasstream_instance_controller.go
This wires the `Cluster` object into all of our controllers. This just works because `Manager` satisfies the `Cluster` interface.
We need this for dry-run as reconcilers will be invoked with a pure `Cluster` object instance in that use case.
> CLOUDP-293806: internal/controller: wire cluster rather than manager

- internal/controller/registry.go
- internal/operator/builder.go
- test/e2e/cache_watch_test.go
- test/e2e/configuration_test.go
- test/e2e/db_users_test.go
- test/e2e/operator_type_wide_test.go
- test/helper/e2e/actions/deploy/deploy_operator.go
- test/helper/e2e/actions/project_flow.go
- test/helper/e2e/k8s/operator.go
This continues making `Cluster` a first class citizen in our code base and centralises controller registration in a central registry, similar to indexers.
Especially the registry is necessary for the dry-run functionality as all controllers will register in a dedicated dry-run manage object.
> CLOUDP-293806: internal/controller: add registry

- internal/translation/deployment/conversion.go
- internal/translation/deployment/conversion_test.go
- internal/translation/networkpeering/networkpeering.go
- test/contract/audit/audit_test.go
- test/contract/networkpeering/networkpeering_test.go
Advanced deployment spec conversion in AKO can nil panic in some cases if:
1. ReplicationSpecs field is set but left empty (spec itself is nil)
2. ReplicationSpecs has empty entries (entries are nil)
3. RegionConfigs are nil
4. RegionConfig entries are nil
This is not a blocker but a major as most customers won't leave empty YAML fields so there is a workaround.
> CLOUDP-296918: fix nil panics in advanced deployment spec

- test/e2e/network_peering_test.go
Order and clean up the test fields to reflect proper usage of the CRD API:
- Remove `RouteTableCIDRBlock` from the GCP test, as it is not used by GCP.
- Remove `AccepterRegionName` from GCP test, as it is has no effect in GCP.
- Replace `AccepterRegionName` with `ContainerRegion` in the Azure test. Even though accepter region acts as a fallback value when container region is not set, it is more correct to use the actual container region field, specially since the accepter region name is an AWS only concept in the API.
- Order the setting fields in all tests to clarify which ones refer to the container configuration and which others affect the peering connection on the app/client side.
> CLOUDP-280230: Fix network peering old tests settings

- .github/workflows/test-contract.yml
- .github/workflows/test-e2e-gov.yml
- .github/workflows/test-e2e.yml
Openshift cluster is already in 4.17
> CLOUDP-297951: Bump kubernetes support version

- internal/controller/atlasproject/custom_roles.go
- internal/controller/atlasproject/custom_roles_test.go
- test/e2e/independent_customroles_test.go
> CLOUDP-298518: Fixed customRoles handler when lastSkipped annotation is not empty

- api/condition.go
- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlasproject/project.go
- internal/controller/atlasproject/project_test.go
- internal/controller/atlasproject/x509_auth.go
- internal/controller/workflow/reason.go
Handle x509 just like other project resources
> CLOUDP-297401: Handle x509 just like other project resources

- internal/controller/atlasproject/network_peering.go
- internal/controller/atlasproject/project.go
- internal/controller/atlasproject/project_test.go
- Do not delete containers when the last applied list is empty, meaning network peerings were not previously managed by the project controller.
- Skip reconciliation of network peerings when the last skipped list is empty, meaning network peerings had been migrated off the project using the skip reconciliation flag beforehand.
- Skip removal of network peerings when the reconciliation is deactivated (last skipped list is empty), otherwise remove only the owned network peers with IDs recorded in the status.
> CLOUDP-298237: Implement greediness deactivation and skips

- internal/controller/atlasbackupcompliancepolicy/atlasbackupcompliancepolicy_controller.go
- internal/controller/atlascustomrole/atlascustomrole_controller.go
- internal/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- internal/controller/atlasdatafederation/datafederation_controller.go
- internal/controller/atlasdeployment/atlasdeployment_controller.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller.go
- internal/controller/atlasipaccesslist/atlasipaccesslist_controller.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller.go
- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlassearchindexconfig/atlassearchindexconfig_controller.go
- internal/controller/atlasstream/atlasstream_connection_controller.go
- internal/controller/atlasstream/atlasstream_instance_controller.go
We have to make sure our custom resources controllers support dry run capabilities. We have the necessary metadata already available already during registration in the regular Manager object, namely the runtime object a reconciler is responsible for.
We need the runtime object for the same reasons controller-runtime needs it in the manager. We need to list resources and act on them during dry-run so the runtime object is needed.
This adds a `For()` method for every reconciler to be used during dry-run.
**Note** This is a no-op, however it's fine to merge this after the 2.7 release.
> CLOUDP-280258: add For() method in all reconcilers for dry-run

- internal/translation/deployment/conversion.go
- internal/translation/deployment/deployment.go
- internal/translation/deployment/deployment_test.go
> CLOUDP-299865: Correctly Generate Connection Secrets for Flex Clusters

- api/v1/atlasdeployment_types.go
- internal/translation/deployment/conversion.go
- test/int/databaseuser_protected_test.go
- test/int/databaseuser_unprotected_test.go
> CLOUDP-299865: Tests for Flex Connection Secrets

- test/int/project_test.go
This fixes potential update conflicts in integration tests for projects. Most notably this fixes a flake like https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/12990969241/job/36227793236?pr=2073:
```
2025-01-27T14:25:31.7198927Z   END STEP: Toggling auto-defer to false - /home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/test/int/project_test.go:610 @ 01/27/25 14:25:29.523 (3ms)
2025-01-27T14:25:31.7199729Z   [FAILED] Expected success, but got an error:
2025-01-27T14:25:31.7200041Z       <*errors.StatusError | 0xc000d3e140>: 
2025-01-27T14:25:31.7200740Z       Operation cannot be fulfilled on atlasprojects.atlas.mongodb.com "test-project": the object has been modified; please apply your changes to the latest version and try again …
```
> CLOUDP-296922: test/int/project: fix conflicting kube updates

- test/int/databaseuser_unprotected_test.go
Currently, we try to do an update of users in the AtlasDatabaseUser integration test before we start retrying. The first update though can fail with a conflict 409 so it becomes a flake.
This fixes it by removing the update and deferring to `RetryUpdateOnConflict` which is one line below.
> CLOUDP-301141: test/int/databaseuser_unprotected_test.go: fix concurrent updates

- internal/dryrun/manager.go
- internal/dryrun/manager_test.go
- internal/operator/builder.go
Currently, Atlas Operator respects the “WATCH_NAMESPACE” environment variable which lets you filter namespaces the operator is watching.
We need to retain this behavior for the dry-run as well as the current code base is wiring cache setup with namespace bindings so we have to respect that in the dry-run manager implementation as well, otherwise behavior will cause errors during the dry-run.
> CLOUDP-301800: dryrun: add support for namespace filtering

- .github/workflows/test-unit.yml
- test/helm/flex_test.go
- test/helm/flex_values.yaml
- test/helper/cmd/cmd.go
- test/helper/decoder/decoder.go
Currently, flex deployments cannot be configured using our helm templates. This fixes it.
This references the changes in https://github.com/mongodb/helm-charts/pull/378.
> CLOUDP-299771: helm: add flex support

- internal/controller/atlas/provider.go
- internal/controller/atlascustomrole/atlascustomrole_controller.go
- internal/controller/atlascustomrole/atlascustomrole_controller_test.go
- internal/controller/atlasdatabaseuser/databaseuser.go
- internal/controller/atlasdatabaseuser/databaseuser_test.go
- internal/controller/atlasdeployment/atlasdeployment_controller.go
- internal/controller/atlasdeployment/atlasdeployment_controller_test.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller.go
- internal/controller/atlasfederatedauth/atlasfederated_auth_controller_test.go
- internal/controller/atlasipaccesslist/atlasipaccesslist_controller_test.go
- internal/controller/atlasipaccesslist/state.go
- internal/controller/atlasipaccesslist/state_test.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller.go
- internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller_test.go
- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlasproject/atlasproject_controller_test.go
- internal/controller/atlasproject/team_reconciler.go
- internal/controller/atlasstream/atlasstream_instance_controller.go
- internal/controller/atlasstream/atlasstream_instance_controller_test.go
- internal/mocks/atlas/provider.go
- internal/translation/client.go
- internal/translation/datafederation/datafederation_test.go
- internal/translation/dbuser/dbuser_test.go
This is the first cleanup PR that addresses the refactoring of the SDK clientset in favor of better semantics. This first change removes the `SdkClient` function in favor of `SdkClientSet` as we want to push using client sets in the code only.
> CLOUDP-294105: atlas/provider: remove SdkClient in favor of SdkClientSet

- .github/workflows/test-e2e.yml
- docs/dev/ci.md
- docs/dev/release.md
This bumps the Kubernetes version test matrix to 1.30-1.32.
> CLOUDP-301799: bump kubernetes versions

- api/v1/alert_configurations.go
- api/v1/alert_configurations_test.go
Allow Serverless Alerts to specify decimal thresholds by @tvdw-mongodb
> CLOUDP-303005: Allow Serverless Alerts to specify decimal thresholds by @tvdw-mongodb

- .github/CODEOWNERS
- OWNERS
This moves OWNERS to .github/CODEOWNERS as per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location and sets up our team for it.
> CLOUDP-298827: move OWNERS to CODEOWNERS

- .github/workflows/cloud-tests.yml
Today, running cloud-tests depends on certain labels but also on the availability to assert codecov comments: https://github.com/mongodb/mongodb-atlas-kubernetes/blob/ca781f006c4ed3367b6e860a9156c26111875705/.github/workflows/cloud-tests.yml#L28-L48
This fails for contributions from forked repositories, i.e. https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2162.
This fixes it.
> CLOUDP-303935: cloud-test.yml: remove dependency from codecov

- api/v1/atlassearchindex_types.go
- bundle/manifests/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- deploy/all-in-one.yaml
- deploy/clusterwide/crds.yaml
- deploy/crds/atlas.mongodb.com_atlasdeployments.yaml
- deploy/namespaced/crds.yaml
- deploy/openshift/crds.yaml
Note: original PR from @segui-mdb https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2193.
Removed duplicate validation entry "lucene.standard" from the search index configuration
> CLOUDP-306112: Removed duplicate validation entry for Search Indexes

- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlasproject/atlasproject_controller_test.go
- internal/controller/atlasproject/custom_roles_test.go
- internal/controller/atlasproject/ipaccess_list.go
- internal/controller/atlasproject/ipaccess_list_test.go
- internal/controller/atlasproject/network_peering.go
- internal/controller/atlasproject/network_peering_test.go
- internal/controller/atlasproject/private_endpoint.go
- internal/controller/atlasproject/private_endpoint_test.go
> CLOUDP-306517: Fix greediness for IP Access List and Network Peerings

- internal/translation/deployment/compare.go
- internal/translation/deployment/compare_test.go
When Scale Down is disabled `ScaleDownEnabled=false`, the Atlas API replies with an empty setting for `MinInstanceSize`, which is an ilegal value to set in the Spec. This means the comparison between the Atlas state and the Kubernetes Spec will always fail and hence the reconciliation loop.
This fix just ignores the value of `MinInstanceSize` for the comparison when `ScaleDownEnabled=false`, so that the reconcile loop is avoided.
Closes #2106
> CLOUDP-286238: Fix autoscale reconcile loop on disabled scale down

- .github/workflows/test.yml
- .github/workflows/trigger.yml
This PR uses a new small `trigger.yml` workflow to handle the logic for both `pull_request` & `pull_request_target` separately of other ways to trigger the `test.yml` workflow. There are only 2 scenarios allowed:
1. The `pull_request` events without the `safe-to-test` label, intended for code owner contributions. Uses the incoming change repo creds, which is the same, as the PR comes from a branch in the same repo.
2. The `pull_request_target` events with `safe-to-test` label that a code owner have just set. Uses the target repo creds, that is the AKO repo creds, and is intended to allow contributions to be tested once a code owner decides it is safe to do so.
> CLOUDP-304211: Only accept pull_request_target with safe-to-test label

- .github/workflows/cloud-tests.yml
- .github/workflows/test-e2e-gov.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test-int.yml
- .github/workflows/test-unit.yml
> CLOUDP-251771: Re-enable Codecov (test coverage) integration

- .github/workflows/test-e2e-gov.yml
- Makefile
- scripts/launch-ci-e2e.sh
> CLOUDP-251771: Enable code coverage integration

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR template for new etiquette guidelines

- internal/controller/atlasproject/atlasproject_controller.go
- internal/controller/atlasproject/atlasproject_controller_test.go
- internal/controller/atlasproject/custom_roles.go
- internal/controller/atlasproject/custom_roles_test.go
- internal/controller/atlasproject/ipaccess_list.go
- internal/controller/atlasproject/ipaccess_list_test.go
- internal/controller/atlasproject/network_peering.go
- internal/controller/atlasproject/private_endpoint.go
- internal/controller/atlasproject/private_endpoint_test.go
- internal/controller/customresource/protection.go
- internal/controller/customresource/protection_test.go
- test/e2e/ipaccesslist_test.go
- test/e2e/privateendpoint_test.go
Replace it by:
- Clearing the resource lists for migrated independent CRDs at skip time. So that they will not eagerly try to take over  the full resource list when skip is removed and potentially conflict with existing independent CRs.
- Without last applied config, non greediness behaviour kicks in and the legacy embedded resource controller will not delete resources from Atlas that does not know about.
Testing: Added one test verifying that migrated resource lists get cleared when the project reconcile is skipped, and several tests cases per migrated resource to verify non greedy behaviour conforms to expectations.
> CLOUDP-299772: Remove last skipped config

- internal/controller/atlasproject/private_endpoint.go
- internal/controller/atlasproject/private_endpoint_test.go
The project reconciler sets a status condition for a resource it does not manage. Without the corresponding configuration, the reconciler is unable to track the resource properly, preventing the project from reaching a ready state.
Incremented unit test covering more greedy behavior cases
> CLOUDP-309306: Project reconciler incorrectly sets PE status for unmanaged resources

- docs/dev/release.md
Update the CLI references in our release guide to refer to the new CLI plugin repo, including a link to the release guide.
> Update release guide for CLI plugin

- .github/workflows/devbox-update.yml
- .github/workflows/sync-helm-charts.yaml
- .github/workflows/update-helm.yaml
- .github/workflows/update-licenses.yml
Fix ako-releaser email on workflows
> CLOUDP-313350: Fix ako-releaser email

- test/e2e/atlas_gov_test.go
- test/int/deployment_test.go
Atlas QA has been slower than usual for the past weeks and this is causing out tests to timeout and the CI pipeline to fail. This tweaks some instance sizes of timing out tests suggests by SREs
CI Should be green.
> CLOUDP-313568: Adjust cluster instances to bypass Atlas slowness

- .github/actions/gen-install-scripts/entrypoint.sh
- bundle.Dockerfile
- docs/dev/ci.md
- scripts/release-redhat-certified.sh
This sets the correct supported OpenShift versions.
> CLOUDP-308490: add supported OpenShift versions

- test/e2e/atlas_gov_test.go
Replace M10 with M20 in gov tests, as the gov QA env does not support M10s anymore in AWS.
Tested locally, but will test CI as well.
> CLOUDP-314621: Use M20 instead of M10 in gov tests

- scripts/create-signed-commit.sh
Must use `base64 -w0` to avoid new lines in commits with long changes. before that, the base64 encoding adding EOLs to the encoded output was breaking requests sent to GitHub.
Also fixed some formatting whitespacing and EOLs.
✅ [Test commit generated in test repo](https://github.com/josvazg/mongodb-atlas-kubernetes/pull/193/commits/82cb78f2ce09850cf20537a580d41abdfd83da54) [Commit generating test job](https://github.com/josvazg/mongodb-atlas-kubernetes/actions/runs/14599365034/job/40953382020)
* **q**: …
> CLOUDP-313350: Fix the commit sign base64 encoding

- internal/controller/atlasproject/teams.go
- internal/controller/atlasproject/teams_test.go
In DRY RUN mode, AKOv2 does not emit Kubernetes events for operations that manage team associations with AtlasProject resources. This is caused by a bug where the underlying error is silently swallowed, preventing proper event reporting. As a result, users receive no indication that an action would have taken place. The expected behavior is that AKOv2 should surface these operations as Kubernetes events when in DRY RUN mode, to maintain full visibility of intended changes.
Unit tests were added
* **q**: …
> CLOUDP-313040: Fix DryRun 

- .github/actions/gen-install-scripts/Dockerfile
- PROJECT
- api/v1/atlasbackupcompliancepolicy_types.go
- config/crd/bases/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- config/crd/bases/atlas.mongodb.com_atlasbackuppolicies.yaml
- config/crd/bases/atlas.mongodb.com_atlasbackupschedules.yaml
- config/crd/bases/atlas.mongodb.com_atlascustomroles.yaml
- config/crd/bases/atlas.mongodb.com_atlasdatabaseusers.yaml
- config/crd/bases/atlas.mongodb.com_atlasdatafederations.yaml
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasfederatedauths.yaml
- config/crd/bases/atlas.mongodb.com_atlasipaccesslists.yaml
- config/crd/bases/atlas.mongodb.com_atlasnetworkcontainers.yaml
- config/crd/bases/atlas.mongodb.com_atlasnetworkpeerings.yaml
- config/crd/bases/atlas.mongodb.com_atlasprivateendpoints.yaml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
- config/crd/bases/atlas.mongodb.com_atlassearchindexconfigs.yaml
- config/crd/bases/atlas.mongodb.com_atlasstreamconnections.yaml
- config/crd/bases/atlas.mongodb.com_atlasstreaminstances.yaml
- config/crd/bases/atlas.mongodb.com_atlasteams.yaml
- config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- config/samples/atlas_v1_atlasbackupcompliancepolicy.yaml
- config/samples/atlas_v1_atlascustomrole.yaml
- config/samples/kustomization.yaml
- devbox.json
- devbox.lock
Red Hat CI raises a couple of warning when evaluating our operator bundle. This PR adjust the project config to address the following warnings:
check_osdk_bundle_validate_operator_framework
check_osdk_bundle_validate_operatorhub
check_required_fields
The warning check_using_fbc was not addressed once it require change the way we package the bundle.
operator-sdk bundle validate ./bundle --select-optional suite=operatorframework
operator-sdk bundle validate ./bundle --select-optional name=operatorhub
operator-sdk bundle validate ./bundle --select-optional name=operatorhubv2
Errors should not be listed by the validation commands above
- Remember the following Communication Standards - use comment …
> CLOUDP-304797: Fix configuration to assess RH warnings

- .github/codecov.yml
- .github/workflows/test-e2e-gov.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test-int.yml
Codecov is assessing all repository paths and tests types, generating confusing reports and blocking PR to be merged.
This configuration exclude E2E and integration tests from coverage, and make it informational (non-blocking merge). 
We should see a realistic number for unit-test coverage. PRs shouldn't be blocked from being merged for wrong reduced coverage.
* --> no prefix is …
> CLOUDP-312253: Configure codecov

- tools/makejwt/go.mod
- tools/makejwt/go.sum
- tools/makejwt/main.go
- tools/makejwt/main_test.go
Upgrade golang-jwt to v5.
This is expected to fix Security Alert [#51 jwt-go allows excessive memory allocation during header parsing](https://github.com/mongodb/mongodb-atlas-kubernetes/security/dependabot/51)
CI should pass
> CLOUDP-315676: Upgrade golang-jwt to v5

- .github/workflows/devbox-update.yml
- scripts/create-signed-commit.sh
Some missing bits breaking the devbox automated updates:
- No **release** env was making secrets inaccesible for the workflow.
- Had to name the local branch properly for the sign commit and push to work properly.
✅ [Manual run worked](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/14693761761)
> CLOUDP-315738: Fixup devbox-update.yml

- .github/workflows/sync-helm-charts.yaml
Fix the path to reach the `create-signed-commit.sh` script properly. The workflow script working directory is not at the root directory of the repo, instead it is at `./helm-charts-cloned` at that point.
TBD
> CLOUDP-315762: Fix workflow path to create-signed-commit.sh

- helm-charts/atlas-deployment/Chart.yaml
- scripts/bump-helm-chart-version.sh
Fixup the deployment chart no tto bump its version with the AKO releases. That was a mistake.
Upon merging, this should NOT create a sync PR in the helm charts repo.
> CLOUDP-317676: Revert not to bump deployment chart with AKO releases

- api/v1/atlasdeployment_types.go
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- test/int/deployment_test.go
Fixed typo in tag values for deployments. This PR resolves: https://github.com/mongodb/mongodb-atlas-kubernetes/issues/2329
> CLOUDP-318983: Fixed typo in tag values for deployments

- api/v1/atlasbackupcompliancepolicy_types.go
- api/v1/atlasbackupcompliancepolicy_types_test.go
This addresses a bug where the `onDemandPolicy` can be missing in the CRD but is still uploaded to Atlas, creating an error.
https://jira.mongodb.org/browse/CLOUDP-317016 ("Backup Compliance Policy erroring with empty retention unit")
> Fix backup compliance policy without onDemandPolicy

- .github/workflows/test-e2e.yml
Remove redundant tag calculation for E2E tests
> Fix: Remove redundant tag calculation for E2E tests

- internal/controller/atlasdatabaseuser/databaseuser.go
- test/e2e/db_users_test.go
This removes the finalizer if the underlying atlas database user is expired, allowing users to delete it.
Unit tests and e2e and int tests are already in place.
> CLOUDP-319574: set finalizer when user is expired

- internal/controller/atlasdeployment/advanced_deployment_test.go
- internal/translation/deployment/conversion.go
- internal/translation/deployment/conversion_test.go
This fixes skew detection if compute autoscaling is disabled but the user still configures remaining autoscaling fields (like instance sizes).
Previously, skew was always detected, causing indefinite reconciles. See the referenced HELP ticket for more details.
Added new unit test and changed existing unit tests reflecting the changed translation layer behavior.
* --> no prefix is …
> CLOUDP-320196: fix skew detection for disabled compute autoscaling

- .github/workflows/test-e2e.yml
- internal/translation/deployment/conversion.go
- internal/translation/deployment/conversion_test.go
Do not forcibly set MongoDBMajorVersion for AtlasDeployment. Atlas sets it to the latest supported major version if this field is not provided in the AtlasDeployment resource
> CLOUDP-302383: Do not forcibly set MongoDBMajorVersion for AtlasDeployment

- .github/workflows/release-post-merge.yml
As part of the AKO and AKO plugin release processes, we'd like the release pipeline to be triggered for only "vX.Y.Z" tags
> CLOUDP-304701: only trigger commits on vX.Y.Z tags

- Makefile
- fast.Dockerfile
This fixes the Makefile to produce multi-arch images, just like the CI already does:
1. Create a `multiarch-builder` buildx builder configured to support multi architecture builds.
2. Build & push using `multiarch-builder` buildx builder for all target platforms at once.
Command `make image VERSION=...` produced a proper prerelease multi-archi image as expected.
* --> no prefix is …
> CLOUDP-323996: Fix make multiarch image

- .github/workflows/cleanup-test.yml
- devbox.json
- devbox.lock
- scripts/openshift-upgrade-test-cleaner.sh
Added an openshift test cleaner to the regular cleaner job
> CLOUDP-221656: Added an openshift test cleaner to the regular cleaner job

- internal/translation/dbuser/conversion.go
- internal/translation/dbuser/internal_test.go
In 140ba21f32fd5c77c2b070b8851b7a7b23a4b2f7 I added the ability to set a description on AtlasDatabaseUser. However, I overlooked that a description could already exist on the user in Atlas, in which case the operator will fetch it, realize it's different, and then... omit the change, because `omitempty` is set on the struct field.
With this patch we send an empty string instead.
> CLOUDP-321083: fix reconciliation loop on dbuser

- internal/controller/atlasthirdpartyintegrations/setup.go
- internal/controller/atlasthirdpartyintegrations/setup_test.go
- internal/controller/registry.go
- internal/controller/registry_test.go
- pkg/controller/state/reconciler.go
- pkg/controller/state/reconciler_test.go
The SetupManagerOption var args did not take into account that options overwrite others each time they are applied in the builder. Instead, we now pass a default options value that can be overridden by each reconciler on the setup function, and otherwise use the defaults given.
TBD
> CLOUDP-316083: Fix initialisation breaking rate limiting

- .github/codecov.yml
- .github/workflows/tests-e2e2.yaml
- test/e2e2/integration_test.go
Compared to failed attempt #2400 :
- Nightlies is still set the `["test/e2e2/*"]` label, but now test selection logic is skipped for such case.
- The special test label `all-e2e2-tests` means *run all tests* and is replaced by an empty label when calling ginkgo.
- Experimental test does not fail when run in a non experimental build, instead it just skips such test.
CI and nightly should be have as expected.
> CLOUDP-325901: Run all test on nightlies (version 2)

- test/e2e2/integration_test.go
As integrations are no longer experimental, they should always run.
Ci should work and execute the e2e2 when `test/e2e2/*` label is set.
> CLOUDP-316083: Let integrations e2e2 run now

- internal/translation/thirdpartyintegration/conversion.go
- internal/translation/thirdpartyintegration/thirdpartyintegration.go
- internal/translation/thirdpartyintegration/thirdpartyintegration_test.go
Atlas API might reply to creation and updates with the whole list of integrations, not just the one created or updated. This fix makes it so that the AKO client code in the translation layer correctly filters out other entries and retains only the one created or updated.
Extra test cases in unit tests validate the new behaviour expected.
> CLOUDP-328306: Find integration in replies

- test/e2e2/ako_test.go
- test/e2e2/all_in_one_test.go
- test/e2e2/integration_test.go
- test/helper/e2e2/kube/kube.go
Disaggregate the kube client creation from the assertion of CRDs
E2e2 should continue to pass after this.
> Disaggregate kube client and CRD asserts

- api/v1/atlasdeployment_types.go
- api/v1/atlasdeployment_types_test.go
- api/v1/atlasproject_types.go
- api/v1/atlasproject_types_test.go
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
When a project is renamed in Kube, the operator will create a new
project and leave the original intact, while other resources (such as
AtlasDeployment) still track the original clusters in the old project.
This leads to bad situations that are difficult to clean up, in
particular via the operator.
Similarly, when a deployment is renamed in Kube a new deployment is
created in Atlas, with the old one left running. Since this is almost
definitely not what the user wanted, let's ensure that name changes here
are also forbidden.
> CLOUDP-330314: Disallow project/deployment renaming

- .github/actions/build-push-image/action.yaml
- .github/actions/image2commit/action.yml
- .github/actions/image2commit/entrypoint.sh
- .github/actions/set-tag/entrypoint.sh
- .github/workflows/promote-image.yml
- .github/workflows/release-branch.yml
- .github/workflows/release-image.yml
- .github/workflows/release-post-merge.yml
- scripts/move-image.sh
Current releases rely on cloud-qa e2e and integration tests which heavily depend on availability of resources in cloud-qa. Releases could be done in a more reliable way by using nightly images, which were previously tested and validated. 
Jira-[CLOUDP-329235](https://jira.mongodb.org/browse/CLOUDP-329235)
> CLOUDP-329235/releasing-images

- .github/workflows/tests-e2e2.yaml
- test/e2e2/flex_to_dedicated_test.go
Ensure nightly and after merge test run the new e2e2 tests for flex to dedicated.
CI will run those tests **after** merge.
> Set flex 2 dedicated nightly tag to run after merge

- scripts/create-signed-commit.sh
> fix: allow for deleted files to be considered when commiting

- .github/workflows/release-image.yml
This change allows us to trigger official release or dryrun pre-releases by selecting the target registry repo to use:
- `official release`-> `mongodb/mongodb-atlas-kubernetes-operator`
- `pre prelease` -> `mongodb/mongodb-atlas-kubernetes-operator-prerelease`
✅ [Managed to produce a pre-release image PR](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2610)  **(NOT MERGED)** 
- See [Successful dry-run release image](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/17126159949)
> CLOUDP-339193: Allow release dryruns

- .github/workflows/release-image.yml
Make sure Operator and CRD Helm Charts image references in the AKO repository get updates to the image version being released.
✅ [Pre-release test generated the deploy and helm](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2614) **(NOT MERGED)**
> CLOUDP-338956: Update Helm Charts & Deploy on Release PR

- test/e2e/private_link_test.go
For some strange reason, local testing found the consistent failure of the affected GCP test was happening on retry. When removing flake retries the issue disappeared.
CI should pass
> CLOUDP-340194: Fix privatelink CI test and typo

- api/v1/atlasdeployment_types.go
- config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml
- internal/translation/deployment/compare.go
- internal/translation/deployment/compare_test.go
- internal/translation/deployment/conversion.go
- internal/translation/deployment/conversion_test.go
This adds the ability to set configServerManagementMode
It should work
> CLOUDP-333238: add configServerManagementMode to AtlasDeployment

- Makefile
- devbox.json
- devbox.lock
1. mockery was not part of any Makefile, now it is
2. The automated devbox upgrade upgraded it to an incompatible version, this pulls it back
3. There was drift so this commit includes the changes
it works
> Downgrade mockery to 2.x, rerun, and add to Makefile

- .github/workflows/cloud-tests.yml
We want Nigthly runs to not be cancelled by merges into main. We also not want merges stopped by PRs. And for PRs each developer can run only one at a time,  one per developer (actor):
- **Nightlies** are **scheduled** in **main** right now. E.g `concurrency.group =cloud-tests-nightly`
- **Merges** are a **push** to **main**. E.g. `concurrency.group = cloud-tests-merge`
- The rest are **PRs** to classify by actor (or triggering actor). E.g. `concurrency.group = cloud-tests-johndoe`
Should verify proper concurrency, but only after this is merged into main.
> CLOUDP-341680: Fix cloud test concurrency

- .github/workflows/test.yml
PRs should not be allowed to build an image even after all tests passed.
Must merge before we can verify it works.
> CLOUDP-341749: Do not build image on a PR

- .github/workflows/license-header-check.yml
- bundle/manifests/atlas.mongodb.com_atlasdeployments.yaml
- bundle/manifests/atlas.mongodb.com_atlasprojects.yaml
- bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- releases/v2.10.0/bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
```shell
cp -r releases/v2.10.0/bundle .
```
This is to fix the `v2.10.0` tag to get the `bundle/` folder updated, so that released versions of CLI plugin can find it as expected using version 2.10.
This will **NOT** merge into main but into the `v.2.10.0-branch`, which should be used to replace the `v2.10.0` tag.
N/A
> Fix v2.10.0: cp released bundle to root dir

- Makefile
In [this PR](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2668), we removed the recompute licenses step from the default make manager target and restricted it to releases only. However, an orphaned make recompute licenses target was left behind, which makes the manager target fail.
> Removal of orphan makefile target

- Makefile
Exclude tools from main AKO sources. 
Should allow tools to be added without breaking the CI tests.
Ci should pass
> Exclude tools from main AKO sources

- .github/workflows/license-header-check.yml
Do not check license headers on toold from main CI. Tools CIs should do that themselves.
CI will be green again in main.
```shell
$ addlicense \
-check \
-l apache \
-c "MongoDB Inc" \
-ignore "**/*.md" \
-ignore "**/*.yaml" \
-ignore "**/*.yml" \
-ignore "**/*.nix" \
-ignore "tools/**" \
-ignore "**/*Dockerfile" . && echo PASS
PASS
```
- [] Have you linked a jira ticket and/or is the ticket in the title?
> Ignore license headers in tools from main CI

- internal/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go
- internal/controller/atlasdatabaseuser/connectionsecrets.go
- internal/controller/atlasdatabaseuser/connectionsecrets_test.go
- internal/controller/atlasdatabaseuser/databaseuser.go
- internal/controller/atlasdatafederation/connectionsecrets.go
- internal/controller/atlasdatafederation/datafederation_controller.go
- internal/controller/atlasdatafederation/datafederation_controller_test.go
- internal/controller/atlasdeployment/advanced_deployment.go
- internal/controller/atlasdeployment/atlasdeployment_controller.go
- internal/controller/secretservice/ensuresecret.go
- internal/controller/secretservice/ensuresecret_test.go
- internal/controller/secretservice/listsecrets.go
- internal/controller/secretservice/listsecrets_test.go
- internal/operator/builder.go
- test/e2e/alert_config_test.go
- test/e2e/atlas_gov_test.go
- test/e2e/encryption_at_rest_test.go
- test/e2e2/integration_test.go
- test/helper/e2e/k8s/k8s.go
- test/int/clusterwide/dbuser_test.go
- test/int/databaseuser_unprotected_test.go
- test/int/datafederation_test.go
- test/int/deployment_test.go
The ConnectionSecret package was originally designed to serve multiple components, including Atlas Data Federation, Atlas Database users, and Atlas Deployments. To better align with its purpose, I have renamed ConnectionSecret to SecretService, as this name more accurately reflects its role. This change also frees up the ConnectionSecret package name, which can now be reused for experimental code in the future. I have also moved some logic only used by AtlasDatabaseUsers in that package.
* **q**: Clarifying …
> Legacy ConnectionSecret refactoring

- .github/workflows/cloud-tests-filter.yml
We no longer run cloud tests in any case when pushing to main. Only the Nightly scheduled or run on demand may do so.
Ci works, merges should not run cloud tests.
> CLOUDP-347174: Don't run cloud tests on push (to main)

- .github/workflows/release-image.yml
Add the checkout so it won't fail like this:
https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/17976950312/job/51132688395
CI should work but test can only be done once merged in main.
> CLOUDP-335401: Checkout the repo to check the version file

- .github/actions/gen-install-scripts/entrypoint.sh
The release needs to take the latest released bundle as a reference to compute the next release bundle.
Tested locally:
```shell
$ ./.github/actions/gen-install-scripts/entrypoint.sh
...
$ tail bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- name: MongoDB Atlas Kubernetes
url: https://github.com/mongodb/mongodb-atlas-kubernetes
maintainers:
- email: support@mongodb.com
name: MongoDB, Inc
maturity: beta
provider:
name: MongoDB, Inc
version: 2.11.0
replaces: mongodb-atlas-kubernetes.v2.10.0
```
* **follow-up**: Can be addressed in a later PR or …
> CLOUDP-335401: Fix bundle update from latest release

- .github/workflows/test-e2e.yml
See changelog for 1.34:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.34.md#changelog-since-v1330
CI should still work.
> CLOUDP-335406: Update test coverage to support Kubernetes 1.32 to 1.34

- .github/workflows/release-image.yml
The version bump must be merged in the post release PR in order to take effect.
A dry run release on this change would update the version.json in the draft PR.
> CLOUDP-335401: Ensure to commit the bumped version.json

- Makefile
- docs/dev/release.md
- scripts/store-sbom-in-s3.sh
Fix the release docs with the learnings from the AKO 2.11.0 issues.
Most code changes were already tested to make the release happen as per the updated instructions.
> CLOUDP-335401: Fixing release docs and scripts

- docs/api-docs.md
- helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasdeployments.yaml
- helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasprojects.yaml
- helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
This should fix the missing pieces from release 
Diff between the releases/v2.11.0/bundle/manifests and helm-charts/atlas-operator-crds CRD files shows nothing.
> CLOUDP-349128: Update helm charts

- internal/v3/translate/names.go
- internal/v3/translate/names_test.go
- internal/v3/translate/ref.go
- internal/v3/translate/translator_test.go
Deterministic outputs are easily testable and follow a similar pattern as already used in generating some Kubernetes names.
CI works.
> Hash translated names with deterministic outputs
