mongodb/mongodb-atlas-kubernetes

.actrc.sample, .github/HOWTO.md, .github/actions/set-tag/Dockerfile, .github/actions/set-tag/action.yml, .github/actions/set-tag/entrypoint.sh, .github/workflows/build-image.yml, .github/workflows/push-test.yml, .gitignore, Dockerfile
=> CLOUDP-77590: build and push Operator image (Init action jobs) copy init-action

.actrc.local.sample, .github/workflows/deploy.yml, Makefile, docs/dev/start-guide.md, go.mod, go.sum
Some changes to support `make int-test`. 
Instructions updated as well
=> Running integration tests using 'make'

.github/workflows/deploy.yml, .github/workflows/push-image.yml, .github/workflows/release-post-merge.yml
Reverts mongodb/mongodb-atlas-kubernetes#32
=> Revert "Bump docker/build-push-action from v1 to v2.2.2"

.github/actions/int-test/entrypoint.sh, config/samples/atlas_v1_atlascluster.yaml, config/samples/atlascluster.yaml, main.go, pkg/api/v1/atlascustomresource.go, pkg/controller/atlascluster/atlascluster_controller.go, pkg/controller/atlascluster/cluster.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/util/testutil/customresources.go, test/int/cluster_test.go, test/int/integration_suite_test.go, test/int/project_test.go
Integration test for cluster.
Tried to make some things (`waitForEvent`, `GetResource`) generic way so different tests could reuse.
Also some more checks and actions are TODO (check connectivity, remove project).
=> CLOUDP-80761: integration test for cluster creation

pkg/controller/atlascluster/atlascluster_controller.go, pkg/util/testutil/customresources.go, test/int/cluster_test.go, test/int/integration_suite_test.go
This is the fix for cluster update flakiness. See descriptions inlined
=> CLOUDP-81194: fix for cluster update flakiness

README.md, config/samples/atlasproject.yaml
Adding IPAccessList to the examples
=> README changes

deploy/all-in-one.yaml
While working on namespaced operator this file was pushed by mistake. It must be changed only while releasing.
=> Revert all-in-one.yaml

Makefile, docs/dev/operator-sdk-notes.md
This should be reviewed/merged after https://github.com/mongodb/mongodb-atlas-kubernetes/pull/129
Adds the Makefile changes and instructions for operator sdk upgrade
=> CLOUDP-83335: Makefile and upgrade notes

pkg/controller/atlasdatabaseuser/databaseuser.go, test/int/dbuser_test.go
The PR removes the old database user from Atlas if the username has changed
=> CLOUDP-84905: support user name change - delete old user

README.md
=> CLOUDP-84837: 0.5.0 Release

config/managerwithproxy/manager_auth_proxy_patch.yaml, docs/dev/release.md, scripts/release-redhat-upstream.sh, scripts/release-redhat.sh
Some automation done of the redhat release process.
=> Some automation for OLM release

.github/workflows/release-post-merge.yml, test/int/cluster_test.go
This PR adds support for releasing quay images right after we release them to dockerhub
=> CLOUDP-87709: releasing quay image

test/e2e/bundle_test.go
=> CLOUDP-88736: remove version def

.github/workflows/lint.yaml, .github/workflows/test.yml, Makefile, test/e2e/actions/steps.go, test/e2e/cli/kube/kubectl.go, test/e2e/configuration_test.go, test/e2e/openshift_test.go
probably fixed geosharded (if it is because long ginkgo await)
change openshift test order (lock earlier)
update kind action (global e2e fails)
=> CLOUDP-92613 flaky

.github/workflows/test.yml, test/e2e/data/atlascluster_basic.yaml, test/e2e/data/atlascluster_basic_update.yaml, test/int/cluster_test.go, test/int/clusterwide/dbuser_test.go, test/int/dbuser_test.go
I removed Tenant from all tests. Please revert it later.
=> Temporary - remove Tenant

.github/actions/cleanup/action.yml, .github/actions/cleanup/entrypoint.sh, .github/actions/int-test/Dockerfile, .github/workflows/cleanup-all.yml, .github/workflows/test-forked.yml, .github/workflows/test.yml, test/e2e/actions/steps.go, test/e2e/cli/helm/helm.go
- Add cluster termination to cleaner
- Add manual workflow for running cleaner
- Add case to helm-update with a different version of charts values file
=> Cloudp-101523: Add cluster termination to cleaner, and manual workflow for it, change helm-update test

pkg/controller/atlascluster/cluster.go, test/int/cluster_test.go
- unset InstanceSizeName if AutoScaling for updates #317
- unset DiskSizeGB if Disk AutoScaling for updates #316
- unset ProviderSettings.AutoScaling when it's disabled #311
=> Unset fields which should be empty for updates

main.go, pkg/controller/atlascluster/atlascluster_controller.go, pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/watch/predicates.go, test/int/clusterwide/integration_suite_test.go, test/int/integration_suite_test.go
This a copy of #278 PR to allow the tests to run.
=> CLOUDP-94516: Testing of Controller Namespace Predicate Changes

test/app/go.sum
Re-fixup with extra `go mod tidy`. Not all packages were cleaned up with the previous try.
=> Update go sum for the test application

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, README.md
Mostly copying from the Community Operator - feedback welcome!
=> CLOUDP-106202: Add Issue & PR templates, and CLA docs

go.mod, go.sum, test/e2e/api/aws/aws.go, test/e2e/config/config.go, test/e2e/private_link_test.go
One of the parts for the PrivateLink test. the test itself - just a sample
=> CLOOUD-90603: for test - work with aws resources

.github/workflows/test-forked.yml, .github/workflows/test.yml, test/e2e/cli/helm/dependency.go, test/e2e/cli/helm/helm.go, test/e2e/cli/helm/prepare_value_file.go, test/e2e/cli/kube/kubectl.go, test/e2e/config/config.go
- changed paths : absolute >> relative
- work with dependency: delete, install separately >> change the source as a file
- remove unsetting for backingProvider from the test (the chart can manage it now without creating a separate value file)
=> CLOUDP-106704: e2e helm-test: dependency as file

pkg/api/v1/status/atlasproject.go, pkg/api/v1/status/zz_generated.deepcopy.go, test/e2e/actions/actions.go, test/e2e/actions/cloud/aws.go, test/e2e/actions/cloud/azure.go, test/e2e/actions/cloud/cloud.go, test/e2e/actions/cloud/gcp.go, test/e2e/actions/deploy/deploy_operator.go, test/e2e/actions/helm_related.go, test/e2e/actions/kube/resources.go, test/e2e/actions/kube/statuses.go, test/e2e/actions/steps.go, test/e2e/api/atlas/atlas.go, test/e2e/api/aws/aws.go, test/e2e/bundle_test.go, test/e2e/cli/kube/kubectl.go, test/e2e/cli/kubecli/kubecli.go, test/e2e/cli/kubecli/kubectl.go, test/e2e/configuration_test.go, test/e2e/helm_chart_test.go, test/e2e/model/project.go, test/e2e/model/user_input.go, test/e2e/multinamespace_test.go, test/e2e/openshift_test.go, test/e2e/operator_type_wide_test.go, test/e2e/private_link_test.go
add a test flow for Private Endpoint
=> CLOUDP-90601: test pe AWS

test/int/project_test.go
please do not merge until the bug fix
UPD: expecting that the problem/bug is gone, so need to merge it for running whose tests  for a while
=> CLOUDP-88816 second deletion test

.github/workflows/test-forked.yml, .github/workflows/test.yml, go.mod, go.sum, test/e2e/actions/cloud/aws.go, test/e2e/private_link_test.go
add test data for several endpoint
=> CLOUDP-109119: e2e: add test data for private endpoint

pkg/controller/atlasproject/atlasproject_controller.go
Co-authored-by: Fulton Byrne <fulton.byrne@commercetools.de>
=> CLOUDP-107373: Delete the finalizer after project soft delete

go.mod
closes https://github.com/mongodb/mongodb-atlas-kubernetes/issues/384
Signed-off-by: Tommy Hughes <tohughes@redhat.com>
=> upgrade to go1.17

.github/actions/cleanup/Dockerfile, .github/actions/cleanup/entrypoint.sh, .github/workflows/cleanup-all.yml, .github/workflows/test-forked.yml, .github/workflows/test.yml
* [+] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
=> CLOUDP-110780: update cleaner

deploy/all-in-one.yaml, deploy/clusterwide/clusterwide-config.yaml, deploy/namespaced/namespaced-config.yaml
This PR fixes the accidentally changed cloud URL for `all-in-one.yaml` deployment
=> Fixed cloud URL

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release-branch.yml, .github/workflows/release-post-merge.yml, docs/dev/release-notes-template.md, docs/release-notes/release-notes.md
This PR introduces a template which can be used to present the release notes.
I manually created this release notes file based on the following commits
Commits:
- removed whitespace
- Added release notes template
- Fixed URL (#419)
- CLOUDP-110604: update ginkgo (#411)
- Update Helm Subrepo (#410)
- CLOUDP-84357: Added single namespace support (#396)
- CLOUDP-110780: update cleaner (#404)
- upgrade to go1.17 (#385)
- Add workflow for releasing post install hook (#403)
- Added helm post install hook (#401)
- CLOUDP-109403: fix openshift test (#397)
- Add label selector to secret watches/cache (Fix E2E issues) (#389)
- e2e: setup timeout for bundle-run
- CLOUDP-107373: Delete finalizer after project soft delete (#388)
- CLOUDP-109859: Prevent Error When Resource Is Deleted (#393)
- …
=> Add Release Notes File and Use in Release Process

.github/workflows/test.yml, config/release/dev/dev_patch.json, go.mod, go.sum, pkg/api/v1/atlascluster_types_test.go, pkg/api/v1/atlasproject_types.go, pkg/controller/atlas/api_error.go, pkg/controller/atlas/client.go, pkg/controller/atlasproject/ipaccess_list.go, pkg/controller/atlasproject/private_endpoint.go, pkg/controller/atlasproject/project.go, test/e2e/api/atlas/atlas.go, test/e2e/config/config.go, test/int/clusterwide/integration_suite_test.go, test/int/integration_suite_test.go
Change log:
* Bumped up `mongodb-atlas` client to `v0.15.0`
* Added `withDefaultAlertSettings` field to the `AtlasProject` structure
* Fixed unit-tests
=> CLOUDP-111964: Added withDefaultAlertSettings field to the AtlasProject structure

pkg/controller/atlasproject/x509_auth.go, scripts/create_kind_cluster.sh, test/e2e/config/kind.yaml, test/e2e/configuration_test.go, test/e2e/data/atlascluster_basic_free.yaml
=> CLOUDP-103755-M0-test

.github/workflows/release-post-install-hook.yml, cmd/post-install/main.go, docs/release-notes/release-notes.md, test/e2e/helm_chart_test.go, test/e2e/model/dataprovider.go
The advanced cluster test was timing out due to this, it was taking longer than 20 minutes to deploy the geosharded cluster.
The test then attempted connectivity which failed.
=> Update Post Install Hook

.github/workflows/release-branch.yml
Fixed release branch. Included golang which is required by the release-notes process.
=> Fixed release branch action

.github/workflows/release-branch.yml
Fixed release-notes generation process
=> Fixed release process

.github/workflows/release-branch.yml
* Added downloading go dependencies for the release process
=> Added downloading go deps for the release process

.github/workflows/release-branch.yml
* Rearranged some steps for create-release action
=> Rearranged some steps for create-release action

config/release/prod/openshift/kustomization.yaml
* Fixed openshift prod deployment
=> Fixed openshift prod deployment

Dockerfile
=> Update all packages in Operator Dockerfile

README.md
* [X ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [N/A ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [N/A ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.
For some steps 1 and 3 the first paragraph was beginning in-line with the step title. I just added newlines.
=> Paragraph formatting

test/e2e/actions/helm_related.go, test/e2e/cli/helm/dependency.go, test/e2e/cli/helm/helm.go, test/e2e/cli/helm/prepare_value_file.go, test/e2e/cli/kubecli/kubecli.go, test/e2e/configuration_test.go
- update submodule (point to last commit)
- fix helm chart update
- cleanup - remove steps for using different version of helm-chart
=> e2e-Helm. Clean up

cmd/manager/main.go, config/manager/manager.yaml
This PR adds custom zap logger with configurable log level and log encoder
Resolves: https://github.com/mongodb/mongodb-atlas-kubernetes/issues/470
=> Added custom logger with levels and encoders

Makefile, pkg/controller/watch/event_handler.go, scripts/e2e_local.sh, test/e2e/actions/steps.go, test/e2e/configuration_test.go, test/e2e/helm_chart_test.go, test/e2e/private_link_test.go, test/int/cluster_test.go
- move couple steps to after block in some test
- makefile - add label/build param for running tests
samples: 
`make int-test label='AtlasCluster && !slow'`
`make e2e label=privatelink-azure-1 build=false` (actually if build equal any symbol)
- fix helm chart log output
- add labels
* [] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
=> CLOUDP-113723-cleanup

.github/actions/cleanup/Dockerfile, .github/actions/cleanup/entrypoint.sh, .github/workflows/build-test-app.yml, .github/workflows/cleanup-all.yml, .github/workflows/deploy.yml, .github/workflows/lint.yaml, .github/workflows/release-branch.yml, .github/workflows/release-post-install-hook.yml, .github/workflows/release-post-merge.yml, .github/workflows/test-forked.yml, .github/workflows/test.yml, go.mod, go.sum, test/e2e/actions/cloud/cloud.go, test/e2e/cli/kubecli/kubecli.go, test/e2e/private_link_test.go
- GitHub action: update MongoDB CLI, action/checkout
- GitHub action: rework cleaner (add more checks, wait deletion)
- GitHub action: add concurrency fields to workflows (need to check). allow cancelling previous run
- test. add for PrivateEnpoint fields additional checks (for showing fails faster)
* [] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
=> CLOUDP-113723: cleanup. part2

test/e2e/helm_chart_test.go
=> for testing advanced-cluster-multiregion-helm

.github/workflows/lint.yaml, config/release/dev/dev_patch.json
=> Change log level for dev by default, update linter

.github/actions/set-tag/entrypoint.sh, .github/workflows/test.yml, go.mod, go.sum
Bumped up `golang.org/x/crypto/ssh` to `v0.0.0-20220411220226-7b82a4e95df4`
=> CLOUDP-119914: Bumped up golang.org/x/crypto/ssh

.gitignore, test/e2e/config/config.go, test/e2e/model/user_input.go
=> CLOUDP-112747: .gitignore

cmd/manager/main.go
=> Added version flag

Makefile
Added automatic `gofmt` and `goimports` when running `fmt` target
=> Added automatic gofmt and goimports when running fmt target

test/e2e/openshift_test.go, test/e2e/ui/openshift/pom/operator_hub.go
=> timeoutShort > timeout

Makefile
Fixed not working `goimports` call for `make fmt` target
=> Fixed not working goimports call for Make fmt target

Dockerfile
This is required so that image can be certified with an A grade
=> CLOUDP-122475: Bumped up UBI to 8.6

.github/actions/cleanup/entrypoint.sh
=> CLOUDP-122569: GitHub action. reaper: delete test global API keys

.github/actions/cleanup/entrypoint.sh, test/e2e/actions/steps.go, test/e2e/api/atlas/atlas.go, test/e2e/helm_chart_test.go, test/e2e/integration_test.go, test/e2e/model/atlas_key_type.go, test/e2e/multinamespace_test.go, test/e2e/private_link_test.go
=> CLOUDP-122569: e2e aftereach global key deletion

.github/actions/cleanup/entrypoint.sh, test/e2e/private_link_test.go
=> CLOUDP-125772-add-gcp-pe-clean

.github/workflows/test-forked.yml, .github/workflows/test.yml, scripts/e2e_local.sh, test/e2e/actions/steps.go
=> CLOUDP-126530: increase update timeout, setup timeout for ginkgo

.github/actions/cleanup/Dockerfile, .github/actions/cleanup/entrypoint.sh
=> CLOUD-126261: Github Action: Add cleaning serverless instances to the cleaner job

.github/workflows/test-forked.yml, .github/workflows/test.yml, test/e2e/configuration_test.go, test/e2e/helm_chart_test.go
=> CLOUDP-126530. split long tests

docs/release-notes/release-notes.md
Forgot to add them in the PR for this feature
=> Add release notes for Maintenance Windows

.github/dependabot.yml, .github/workflows/test-forked.yml
=> fix dependabot

pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/deployment.go
This PR resolves https://github.com/mongodb/mongodb-atlas-kubernetes/issues/589
=> Fixed panic when Atlas API returns an empty object

.github/workflows/test-e2e.yml, test/e2e/actions/steps.go, test/e2e/helm_chart_test.go
Fix ginkgo label filter value.
Update operator-sdk version to 1.22.0. 
Remove observed generation check in case this check is meaningless.
=> CLOUDP-128685: Fix e2e tests

test/e2e/openshift_test.go, test/e2e/ui/openshift/pom/login.go, test/e2e/ui/openshift/pom/navigate_links.go
please, delete lines `todo //to delete` and change repo secrets
=> CLOUDP-127149: Migrate Openshift UI test to 4.10 cluster

config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml, pkg/api/v1/atlasdeployment_types.go
=> Small documentation fixes for Atlas Deployments

.github/workflows/openshift-upgrade-test.yaml
Renamed Openshift upgrade test workflow
=> Renamed Openshift upgrade test workflow

config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml, pkg/api/v1/atlasdeployment_types.go, pkg/api/v1/zz_generated.deepcopy.go, pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/advanced_deployment_test.go, test/int/deployment_test.go
=> CLOUDP-130484: Refactor the Advanced Deployment Handler

.github/workflows/openshift-upgrade-test.yaml
=> Fixed missing OC token

scripts/openshift-upgrade-test.sh
Fixed Openshift upgrade test compatibility with Linux
=> Fixed Openshift upgrade test compatibility with Linux

Makefile
=> Remove redundant "go init"

.github/workflows/openshift-upgrade-test.yaml, Makefile
Fixed `kustomize` tool downloader
=> Fixed Kustomize downloader

.github/workflows/openshift-upgrade-test.yaml
Fixed missing operator-sdk for Openshift upgrade test
=> Fixed missing operator-sdk

.github/workflows/openshift-upgrade-test.yaml
Fixed operator upgrade test workflow
=> Fixed operator upgrade test workflow

.github/workflows/openshift-upgrade-test.yaml
Bumped up OPM to 4.9 for the Openshift upgrade test
=> Bumped up OPM to 4.9

.pre-commit-config.yaml, scripts/create_x509.go, test/app/main.go, test/e2e/appclient/test_app_client.go, test/e2e/cli/helm/dependency.go, test/e2e/utils/utils.go
Remove deprecated io/ioutil package
=> Update pre-commit config

README.md, docs/dev/release.md
The word "certain" starts with `c` 🙃
=> Improve the release doc and fix the typo

pkg/util/testutil/customresources.go, test/int/clusterwide/dbuser_test.go, test/int/dbuser_test.go, test/int/deployment_test.go, test/int/project_test.go
=> CLOUDP-120528: Refactor integration tests

.github/workflows/test-forked.yml
=> Change pull_request_target event to pull_request

.github/workflows/test-forked.yml
=> Revert change pull_request_target event to pull_request

test/e2e/actions/helm_related.go, test/e2e/actions/steps.go, test/e2e/cli/kubecli/kubecli.go, test/e2e/e2e_suite_test.go, test/e2e/helm_chart_test.go, test/e2e/private_link_test.go, test/e2e/x509_test.go
Fix some typos and remove unused function args
=> Test suite minor fixes

pkg/controller/atlasdeployment/atlasdeployment_controller.go, test/e2e/cloud_access_role_test.go, test/e2e/network_peering_test.go
=> CLOUDP-135171: Fix error message for Delete method

config/crd/bases/atlas.mongodb.com_atlasprojects.yaml, pkg/api/v1/cloud_provider_access.go
=> Remove unnecessary validation for cloud access role

config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
=> CLOUDP-131964: Change capability level to 3rd (Full Lifecycle)

pkg/api/v1/status/cloud_provider_access.go, pkg/controller/atlasproject/cloud_provider_access.go
Fix a bug when there are multiple roles with the same ARN.
Fix a bug when a role with an empty ARN changes its atlasAssumedRoleExternalId after editing.
=> Cloud access role fix

.github/workflows/test-forked.yml
=> Fix forked test allowed job name

test/int/clusterwide/dbuser_test.go, test/int/dbuser_test.go, test/int/deployment_test.go, test/int/project_test.go
=> CLOUDP-136194: Refactor validator using Gomega

.github/actions/cleanup/entrypoint.sh
Remove network peering connections before removing projects
=> CLOUDP-136573: Remove network peering connections

.github/actions/cleanup/entrypoint.sh
=> CLOUDP-136573: Fixed cleaner

.github/workflows/release-certify.yaml
Fixed operator image certification job trigger
=> Fixed operator image certification job

.github/workflows/cleanup-all.yml
=> Add scheduled cleanup

pkg/api/v1/project/ipaccesslist.go, pkg/controller/atlasproject/ipaccess_list.go, test/e2e/data/atlasproject.yaml, test/e2e/model/project.go, test/int/clusterwide/dbuser_test.go, test/int/dbuser_test.go, test/int/deployment_test.go
Add validation for ip access list
closes #694
=> CLOUDP-137881: Fix issue with /32 CIDR

.github/workflows/cleanup-all.yml
=> CLOUDP-138351: Set the default false for tagged PE cleaner

cmd/manager/main.go, pkg/controller/atlasproject/encryption_at_rest.go, test/e2e/actions/steps.go, test/e2e/integration_test.go, test/e2e/multinamespace_test.go
Fixed multi-namespace configuration for the manager
=> CLOUDP-134644: Fixed multi-namespace configuration for the manager

.github/actions/set-tag/entrypoint.sh, .github/workflows/build-test-app.yml, .github/workflows/cleanup-all.yml, .github/workflows/deploy.yml, .github/workflows/lint.yaml, .github/workflows/openshift-upgrade-test.yaml, .github/workflows/release-branch.yml, .github/workflows/release-certify.yaml, .github/workflows/release-post-install-hook.yml, .github/workflows/release-post-merge.yml, .github/workflows/remove-label.yml, .github/workflows/test-e2e.yml, .github/workflows/test-int.yml, .github/workflows/test-unit.yml
=> Update deprecated GitHub actions commands

config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
=> CLOUDP-84838: Enable multinamespace for bundle

OWNERS
Added Helder to the list of OWNERS
=> Added Helder to the list of OWNERS

.github/workflows/release-post-merge.yml
=> Fix GitHub action workflow file

.github/workflows/release-post-merge.yml
=> Fix release post merge push

test/e2e/actions/steps.go, test/e2e/network_peering_test.go
Increased timeout for establishing peer connection
=> Increased timeout for establishing peer connection

bundle.Dockerfile
Fixed Openshift version range for the operator bundle
=> Fixed Openshift version range for the operator bundle

docs/dev/release.md, scripts/release-redhat-certified.sh
Updated Openshift image certification instructions
=> CLOUDP-140768: Updated Openshift image certification instructions

test/e2e/actions/networkpeer/azure.go, test/e2e/actions/networkpeer/gcp.go, test/e2e/network_peering_test.go
=> CLOUDP-141796: Fix network peering test names

.github/workflows/release-branch.yml, .github/workflows/release-post-merge.yml
* [x ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
=> CLOUDP-141994: Fix create release job

.github/actions/gen-install-scripts/entrypoint.sh, bundle.Dockerfile, bundle/metadata/annotations.yaml
Fixed minimum version of Openshift (4.8)
=> Fixed minimum version of Openshift (4.8)

.github/workflows/release-post-merge.yml
=> Fix create release workflow

pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go, pkg/controller/atlasdatabaseuser/databaseuser.go, pkg/controller/atlasdeployment/deployment.go, pkg/controller/connectionsecret/connectionsecrets.go, test/int/dbuser_test.go
=> Fix connection secret creation

.github/workflows/cleanup-all.yml, test/e2e/actions/serverlessprivateendpoint/spe.go
=> Fix PE cleaning

test/e2e/cli/helm/helm.go
=> Bumped up helm-charts to 1.5

pkg/controller/connectionsecret/connectionsecrets.go
=> CLOUDP-149877: Add connection string creation for serverless instance

pkg/controller/atlasproject/teams.go
Fixed nil pointer dereference for AtlasTeams
=> Fixed nil pointer dereference for AtlasTeams

pkg/controller/atlasdeployment/serverless_private_endpoint.go
Fix SPE for serverless spec like this (with provider name in providerName field, but not in a backingProviderName):
```
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
name: atlas-deployment-serverless
spec:
projectRef:
name: my-project
serverlessSpec:
name: serverless-instance-7
providerSettings:
providerName: AWS
regionName: US_EAST_1
```
=> Fix provider choice function for SPE

.github/workflows/release-branch.yml
successful run: https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/3748964554/jobs/6366899455
=> Fix go-licenses for latest version

.github/actions/int-test/Dockerfile, .github/workflows/test-e2e.yml
=> Fix ginkgo warnings

.github/workflows/test-e2e.yml, pkg/controller/atlasproject/network_peering.go, pkg/util/comparation.go, test/e2e/actions/conditions.go, test/e2e/auditing_test.go, test/e2e/custom_roles_test.go, test/e2e/encryption_at_rest_test.go, test/e2e/integration_test.go, test/e2e/network_peering_test.go, test/e2e/project_settings_test.go, test/e2e/teams_test.go
=> CLOUDP-151638: Fix network peer container handling

pkg/api/v1/provider/provider.go, pkg/controller/atlasdeployment/serverless_private_endpoint.go
=> Fix GCP SPE

config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
=> Add CSV multi-arch labels

.github/actions/build-push-image/action.yaml, .github/workflows/test-e2e.yml
=> Add cache to e2e tests

pkg/controller/atlasproject/encryption_at_rest.go
Fixed not working Google KMS for Encryption at REST feature
=> CLOUDP-153000: Fixed not working Google KMS for Encryption at REST feature

pkg/controller/atlasproject/ipaccess_list.go, pkg/controller/atlasproject/ipaccess_list_test.go
=> Remove ip access list validator

.golangci.yml, config/crd/bases/atlas.mongodb.com_atlasbackupschedules.yaml, pkg/api/v1/atlasbackupschedule_types.go, pkg/controller/atlasdeployment/backup.go, test/int/dbuser_test.go
Fixed BackupSchedule reconciliation
=> CLOUDP-153756: Fixed BackupSchedule reconciliation

.github/workflows/release-post-merge.yml
=> Add comment to release post merge workflow

pkg/api/v1/atlasproject_types.go, pkg/api/v1/zz_generated.deepcopy.go, test/e2e/model/project.go, test/e2e/multinamespace_test.go
Make connection secret namespaced resource
=> CLOUDP-154088: Make connection secret namespaced resource

.github/workflows/test-e2e.yml, pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/deployment.go, test/e2e/data/deployments.go, test/e2e/free_tier_test.go
=> CLOUDP-155410: Fix operator bug with existing m0 cluster

config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
Added optional namespace parameter for `connectionSecretRef`
=> CLOUDP-154088: Fixed AtlasProject CRD base. Added optional namespace parameter

.github/actions/certify-openshift-images/action.yaml, .github/actions/certify-openshift-images/entrypoint.sh, .github/workflows/release-openshift.yaml, Dockerfile
=> Fix image security issue / adjust certification check

test/e2e/actions/cloud/aws.go, test/e2e/api/aws/aws.go
=> CLOUDP-164203: Improve private endpoint tests

go.mod, go.sum, pkg/api/v1/atlasdeployment_types.go, pkg/api/v1/atlasdeployment_types_test.go, pkg/controller/atlasdatabaseuser/databaseuser.go, pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/advanced_deployment_test.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/deployment.go, pkg/controller/atlasdeployment/deployment_test.go, pkg/util/testutil/atlas.go, test/e2e/actions/actions.go, test/e2e/actions/annotations_related.go, test/e2e/actions/helm_related.go, test/e2e/actions/steps.go, test/e2e/api/atlas/atlas.go, test/e2e/global_deployment_test.go, test/e2e/helm_chart_test.go, test/int/clusterwide/dbuser_test.go, test/int/dbuser_test.go, test/int/deployment_test.go, test/int/project_test.go
This is the move to the Advanced Cluster API, legacy cluster API calls are changed to advanced cluster API calls.
=> CLOUDP-147254: Use only Advanced Cluster API

pkg/api/v1/atlasproject_types.go
Do not print credentials for AtlasProject resources
=> CLOUDP-166250: Do not print credentials for AtlasProject resources

pkg/controller/atlasproject/atlasproject_controller.go
Fixed AtlasProject reconcile loop so it won't prevent processing of other features if one feature is not configured correctly.
=> CLOUDP-165710: Fixed AtlasProject reconcile loop

docs/dev/release.md
Added a note about triggering releases
=> CLOUDP-169875: Updated release.md

pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/advanced_deployment_test.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/connectionsecret/listsecrets.go, test/e2e/actions/deploy/deploy_operator.go, test/e2e/data/user.go, test/e2e/db_users_test.go, test/int/deployment_test.go
=> CLOUDP-167740: Fix connection secrets generation for DBUsers in separated namespaces

.github/actions/build-push-image/action.yaml, .github/workflows/build-test-app.yml, .github/workflows/test-e2e.yml, test/app/Dockerfile
=> CLOUDP-166507: Migrate images on docker hub mongodbinternal org to quay.io

.github/workflows/release-post-merge.yml
Tag the release also with `{version}-certified` for openshift certified operators
=> CLOUDP-167111: Add certified tag

.github/workflows/build-test-app.yml, .github/workflows/cleanup-all.yml, .github/workflows/deploy.yml, .github/workflows/lint.yaml, .github/workflows/openshift-upgrade-test.yaml, .github/workflows/release-branch.yml, .github/workflows/release-openshift.yaml, .github/workflows/release-post-install-hook.yml, .github/workflows/release-post-merge.yml, .github/workflows/stale.yml, .github/workflows/test-e2e.yml, .github/workflows/test-int.yml, .github/workflows/test-unit.yml, .github/workflows/test.yml
=> Update Github actions

.github/actions/build-push-image/action.yaml, .github/workflows/rebuild-released-images.yaml, daily-builds.json
=> CLOUDP-161447: Add daily builds

.github/workflows/release-branch.yml, .github/workflows/test.yml, go.mod, go.sum
=> CLOUDP-175919: Fix Test pipeline for release PRs

.github/workflows/rebuild-released-images.yaml
=> CLOUDP-161447: Fixed daily builds

Dockerfile
Bumped up `ubi-minimal` to 8.8
=> Bumped up ubi-minimal to 8.8

.github/dependabot.yml, .github/workflows/release-branch.yml, .github/workflows/release-openshift.yaml, OWNERS
Updated repo owners and CI reviewers
=> Updated repo owners and CI reviewers

test/app/go.mod, test/app/go.sum
Attempt to fix #1001 from scratch.
=> Upgrade test app golang/x/text to v0.3.8

.github/workflows/lint.yaml, .golangci.yml
=> Chore: Bump golangci-lint version and configure depguard

pkg/controller/atlasproject/encryption_at_rest.go
=> Fixed AWS KMS normalization

test/e2e/alert_config_test.go
Fixed error with missing DATADOG_KEY for a local test run
=> Fixed error with missing DATADOG_KEY for a local test run

pkg/controller/atlasdeployment/atlasdeployment_controller.go
=> CLOUDP-188897: return after deployment removal

Makefile, pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/backup.go, pkg/controller/atlasproject/alert_configurations.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/teams.go, pkg/controller/workflow/context.go
AtlasProject controller to watch secrets for alert configurations
=> CLOUDP-186825: AtlasProject controller to watch secrets for alert configurations

test/e2e/actions/deploy/deploy_operator.go, test/e2e/fixtest/remove_duplicates.go
=> CLOUDP-188083: Autorecover from duplicate project in tests

pkg/controller/customresource/customresource.go, pkg/controller/customresource/protection_test.go
=> Add unit tests to protection primitives

config/crd/bases/atlas.mongodb.com_atlasprojects.yaml
Fixed missing CRD changes for EaR secret refs
=> Fixed missing CRD changes for EaR secret refs

pkg/api/v1/status/cloud_provider_access.go, pkg/controller/atlasproject/cloud_provider_access.go, pkg/controller/atlasproject/cloud_provider_access_test.go, test/e2e/actions/project_flow.go, test/e2e/backup_config_test.go, test/e2e/cloud_access_role_test.go, test/e2e/project_deletion_protection_test.go, test/int/databaseuser_unprotected_test.go
=> CLOUDP-195419: Improve Cloud Provider Access reconciliation flow

pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/maintenancewindow.go, pkg/controller/atlasproject/team_reconciler.go, pkg/controller/atlasproject/team_reconciler_test.go, pkg/controller/atlasproject/teams.go, test/e2e/project_deletion_protection_test.go
=> CLOUDP-178752: Deletion protection for Atlas Teams CR

.github/workflows/cleanup-all.yml, .github/workflows/test-e2e.yml, pkg/controller/atlasproject/encryption_at_rest.go, test/e2e/actions/cloud/aws.go, test/e2e/e2e_suite_test.go, test/e2e/encryption_at_rest_test.go, test/e2e/project_deletion_protection_test.go
=> CLOUDP-197433: Fix Encryption at Rest flakiness

pkg/controller/atlas/ip_access_list.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/ipaccess_list.go, pkg/controller/atlasproject/ipaccess_list_test.go, pkg/controller/validate/validate.go, pkg/controller/validate/validate_test.go
=> CLOUDP-192060: Avoid recreate IPAccessList every reconciliation

go.mod, go.sum, pkg/api/v1/atlasbackupschedule_types.go, pkg/api/v1/atlasbackupschedule_types_test.go, pkg/api/v1/atlascustomresource.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/backup.go, pkg/controller/atlasdeployment/backup_test.go, pkg/util/toptr/toptr.go, test/int/backup_protected_test.go, test/int/deployment_protected_test.go
=> CLOUDP-178753: Deletion protection for AtlasBackupSchedule and AtlasBackupPolicy

pkg/controller/validate/validate_test.go
Orca was complaining because there appeared to be valid private keys in code. They were removed but automation cannot know that, so it is better to autogenerate the private key for these validation tests.
* ~Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one)~.
* ~Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release~.
=> CLOUDP-201141: Fix Orca complain on fake test private keys

.env.sample, docs/dev/start-guide.md, dotenv.sample
* ~Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one)~.
* ~Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release~.
=> CLOUDP-201549: Rename .env.sample to dotenv.sample and comment

pkg/api/v1/custom_roles_test.go, pkg/controller/atlasdeployment/backup.go, pkg/controller/atlasdeployment/backup_test.go
=> CLOUDP-201374: Fix backup schedule repeatedly updating

pkg/controller/atlasproject/teams.go, pkg/controller/atlasproject/teams_test.go
=> CLOUDP-201563: Duplicate Projects Listed in Teams Status

pkg/controller/validate/validate.go, pkg/controller/validate/validate_test.go, test/e2e/alert_config_test.go
* ~Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one)~.
* ~Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release~.
=> CLOUDP-202681: Validate away duplicate alter configs

docs/dev/release.md, scripts/release-redhat-certified.sh
=> CLOUDP-205249: Fix release doc & script from recent release experience

.github/workflows/test-e2e.yml
=> CLOUDP-204395: Recover from repo cache miss on e2e test

config/crd/bases/atlas.mongodb.com_atlasbackupschedules.yaml, pkg/api/v1/atlasbackupschedule_types.go, pkg/api/v1/atlasbackupschedule_types_test.go, pkg/api/v1/atlasdeployment_types.go, pkg/api/v1/zz_generated.deepcopy.go, pkg/controller/atlasdeployment/backup.go, pkg/controller/atlasdeployment/backup_test.go, pkg/controller/validate/validate.go, pkg/controller/validate/validate_test.go, pkg/controller/watch/watched_resource_handler.go, test/int/deployment_test.go
=> CLOUDP-204494: Improve snapshot distribution management

.github/actions/certify-openshift-images/entrypoint.sh
=> CLOUDP-205246: Fix Openshift certification action

.github/workflows/paths-filter.yml
=> Trigger expensive tests when changed

config/rbac/clusterwide/role.yaml, config/rbac/namespaced/role.yaml, deploy/all-in-one.yaml
=> Fix all-in-one.yaml ClusterRole

config/rbac/clusterwide/role.yaml, config/rbac/namespaced/role.yaml, deploy/all-in-one.yaml
=> CLOUDP-208072: Fix all-in-one.yaml ClusterRole to release 1.9.1

scripts/release-redhat-certified.sh
=> CLOUDP-208213: Fix OpenShift certified push

docs/dev/release.md
=> CLOUDP-208614: Document PR fixes for release

pkg/controller/customresource/customresource.go
=> CLOUDP-207934: Fixed resource version label

.github/actions/gen-install-scripts/entrypoint.sh, Makefile, pkg/api/v1/alert_configurations.go, pkg/api/v1/atlasproject_types.go, pkg/api/v1/common/common.go, pkg/api/v1/encryption_at_rest.go, pkg/controller/atlasproject/alert_configurations.go, pkg/controller/atlasproject/encryption_at_rest.go, pkg/controller/atlasproject/encryption_at_rest_test.go, pkg/controller/validate/validate.go, pkg/controller/validate/validate_test.go, test/e2e/atlas_gov_test.go, test/e2e/encryption_at_rest_test.go, test/e2e/project_deletion_protection_test.go
=> CLOUDP-205479: Force secretRef fields

pkg/api/v1/alert_configurations.go
=> Clean up err return in alert configurations

go.work
Removed go.work as it breaks licences generation
=> Removed go.work

.github/workflows/cleanup-all.yml
=> fix(cleanup workflow): project lifetime default value

.github/actions/build-push-image/action.yaml, .github/actions/certify-openshift-images/entrypoint.sh, .github/workflows/release-post-merge.yml, .github/workflows/test-e2e.yml
=> Fixed Docker build-push-image

.github/workflows/test-e2e.yml
=> Push bundle image to quay.io on E2E tests

.actrc.local.sample, .github/HOWTO.md, .github/workflows/test-e2e.yml
=> CLOUDP-202467: Remove unused OpenShift credentials

.github/actions/build-push-image/action.yaml, .github/workflows/test-e2e.yml, test/e2e/cli/helm/helm.go
=> Use ghcr for e2e tests

config/crd/bases/atlas.mongodb.com_atlasprojects.yaml, scripts/deploy.sh
=> CLOUDP-205479: Fixed missing changes for the AtlasProject crd

.github/workflows/cleanup-all.yml
Reduce the default lifetime of a project. 3h seems to be too long.
Added the ability to run in one or both envs.
=> Improve clean-up workflow

.github/workflows/cleanup-all.yml
=> Fix parameter values for schedule events

.github/workflows/cleanup-all.yml, tools/clean/atlas/atlas.go, tools/clean/atlas/clusters.go, tools/clean/atlas/data_federation.go, tools/clean/atlas/encryption_at_rest.go
=> Cleanup fix and improvements

tools/clean/atlas/atlas.go, tools/clean/atlas/network_peering.go, tools/clean/atlas/projects.go
=> CLOUDP-212108: Fix Net Peerings part 2

cmd/manager/main.go, internal/mocks/atlas/cloud_provider_access.go, internal/mocks/atlas/global_clusters.go, internal/mocks/atlas/provider.go, pkg/controller/atlas/provider.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/atlasdeployment_controller_test.go, pkg/controller/atlasdeployment/backup.go, pkg/controller/customresource/customresource.go, test/helper/e2e/k8s/operator.go, test/int/clusterwide/integration_suite_test.go, test/int/integration_suite_test.go, tools/clean/provider/gcp.go
=> chore: Testable controllers

.github/workflows/rebuild-released-images.yaml, .github/workflows/release-post-merge.yml, Makefile, scripts/module-path.sh, scripts/version-check.sh
✅ [Test Daily rebuild produces properly named versions](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/7259900211)
✅ [Test Create release checked the version correctly](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/7259948569)
=> CLOUDP-218515: Enforce binary version release correctness

test/app/go.mod, test/app/go.sum
Manual apply as I wrongly closed #1290
=> Bump golang.org/x/crypto in /test/app

docs/dev/ci.md
=> CLOUDP-219313: Document test kube version

.github/workflows/rebuild-released-images.yaml, Makefile
Fix version setting on rebuilds.
✅ [Rebuild version correctly set from matrix version](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/7398216680/job/20126922986)
=> CLOUDP-219167: Fix version setting at rebuilds

.golangci.yml, pkg/api/v1/alert_configurations.go, test/e2e/atlas_gov_test.go, test/e2e/datafederation_pe_test.go, test/e2e/db_users_oidc.go, test/e2e/db_users_test.go, test/e2e/project_deletion_protection_test.go, test/helper/access/ipaccesslist_matcher.go, test/helper/atlas/waiters.go, test/helper/conditions/conditions.go, test/helper/events/events.go, test/helper/maintenance/maintenancewindow_matcher.go, test/helper/resources/customresources.go, test/int/backup_protected_test.go, test/int/clusterwide/dbuser_test.go, test/int/databaseuser_protected_test.go, test/int/databaseuser_unprotected_test.go, test/int/datafederation_protect_test.go, test/int/datafederation_test.go, test/int/deployment_protected_test.go, test/int/deployment_test.go, test/int/deployment_unprotected_test.go, test/int/federated_auth_test.go, test/int/project_protect_test.go, test/int/project_test.go
=> CLOUDP-221195: Move testutils to test/helpers

.github/workflows/cleanup-all.yml
=> Chore: Update Azure credentials on CleanUp workflow

.github/workflows/reports.yml
=> CLOUDP-22246: Allow report CI to be called manually

pkg/controller/atlasproject/atlasproject_controller.go
=> CLOUDP-227244: Use new SDK in Atlas Project Controller

.github/workflows/release-post-merge.yml
=> CLOUDP-226369: Fix pre-release testing for backports

pkg/api/v1/networkpeer.go, pkg/api/v1/status/networkpeer.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/network_peering.go
=> CLOUDP-222247: Migrate AtlasProject Controller: Migrate Network Peering

.github/workflows/cloud-tests.yml
=> Run gov tests also on push

pkg/api/v1/status/atlasproject.go, pkg/controller/atlasproject/private_endpoint.go
=> CLOUDP-221151: Fix function name typos

.github/workflows/openshift-upgrade-test.yaml, docs/dev/ci.md
=> Add condition to skip OpenShift test

test/e2e/atlas_gov_test.go
✅ [Gov e2e tests passed again](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8065610609/job/22031781580)
=> CLOUDP-234039: Fix Gov e2e tests

.github/workflows/update-licenses.yml
=> CLOUDP-231603: Fix bot permission to commit

config/manifests/bases/mongodb-atlas-kubernetes.clusterserviceversion.yaml
**Note**
* All features were added except for the cnf/cni/csi variants, as per documentation
* Set disconnected to false as our operator doesn't make sense without an internet connection
* Set fips-compliant to false. While we support Gov and Fips is usually a requirement of Gov users, we don't have any test validating such a scenario.
=> CLOUDP-233562: Add infrastructure annotations to Openshift CSV

test/int/integration_suite_test.go
=> test/int: disable ownership detection

pkg/api/v1/atlasfederatedauth_types.go, pkg/api/v1/atlasfederatedauth_types_test.go, test/int/federated_auth_test.go
=> CLOUDP-236434: Fix role mapping patch in FedAuth

.github/actions/build-push-image/action.yaml, .github/workflows/check-licenses.yml, .github/workflows/cloud-tests-filter.yml, .github/workflows/lint.yaml, .github/workflows/openshift-upgrade-test.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-int.yml, .github/workflows/test-unit.yml, .github/workflows/test.yml, .github/workflows/validate-manifests.yml
If not explicit, on some PR or push events it might checkout main instead, which is not what we want on PR tests.
=> Ensure tests checkout PR branch

tools/clean/atlas/atlas.go, tools/clean/main.go, tools/clean/provider/gcp.go
=> CLOUDP-238207: tools/clean: add VPC orphan cleanup

.github/workflows/rebuild-released-images.yaml
✅  [test rebuild of version 2.2.0 with signing](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/8387533463/job/22969903989)
=> Fix rebuild artifactory access

README.md
=> Test a dummy pre-release

README.md
=> Test pre-release again

config/manager/manager.yaml
=> CLOUDP-239117: Set RAM request to 256Mi

.github/workflows/test-int.yml, internal/pointer/pointer.go, pkg/api/v1/privateendpoint.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/private_endpoint.go, pkg/controller/atlasproject/private_endpoint_test.go, test/helper/e2e/actions/cloud/gcp.go, test/int/deployment_test.go
=> CLOUDP-228583: migrate private endpoints to new Atlas SDK

bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
=> [Pre-release test]

README.md, docs/dev/signed-images.md
This is the developers focused doc. I intend to ask for official public facing documentation based on this instructions.
=> CLOUDP-240936: Document image signature verification

pkg/api/v1/status/serverless_private_endpoint.go, pkg/controller/atlasdeployment/serverless_private_endpoint.go, pkg/controller/atlasdeployment/serverless_private_endpoint_test.go, pkg/controller/validate/validate.go
=> CLOUDP-240782: Improvements on serverless private endpoint refactor

.github/workflows/release-post-merge.yml, .github/workflows/tag.yml
- Pass access to secrets on the workflow call.
- Ensure proper signature by setting the repository name environment variable.
=> CLOUDP-243462: Fix release workflows

scripts/generate_upload_sbom.sh
Add SBOM generation and S3 push script for future use.
=> CLOUDP-241390: Generate upload SBOM script

docs/releases/v2.2.1/linux-amd64.sbom.json, docs/releases/v2.2.1/linux-arm64.sbom.json, docs/releases/v2.2.1/sdlc-compliance.md
See [sdlc-compliance.md](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/CLOUDP-239203/release-checklist-221/docs/releases/v2.2.1/sdlc-compliance.md) following [this as an example](https://gist.github.com/rtimmons/8253d1dfcc5f233bdb2d9c73b8e5c129)
=> CLOUDP-239203: Release 2.2.1 SSDLC checklist

docs/dev/release.md
=> CLOUDP-230380: Improve Release documentation

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release-post-merge.yml
=> Fix Release job

Makefile, docs/dev/release.md, docs/releases/sdlc-compliance.template.md, scripts/gen-sdlc-checklist.sh
=> CLOUDP-245405: Generate SDLC checklist

docs/releases/v2.2.2/linux-amd64.sbom.json, docs/releases/v2.2.2/linux-arm64.sbom.json, docs/releases/v2.2.2/sdlc-compliance.md
=> add SBOM for 2.2.2

.github/workflows/test-int.yml, cmd/manager/main.go, config/samples/atlas_v1_atlasstreamconnection.yaml, config/samples/atlas_v1_atlasstreaminstance.yaml, pkg/controller/atlasstream/atlasstream_connection_controller.go, pkg/controller/atlasstream/atlasstream_connection_controller_test.go, pkg/controller/atlasstream/atlasstream_instance_controller.go, test/int/atlas_streams_test.go, test/int/integration_suite_test.go
=> CLOUDP-238528: Atlas stream connection controller

.github/workflows/test-e2e.yml, docs/dev/ci.md
Update CI docs with more workflow details and direct links.
=> CLOUDP-246313: Update CI docs with more details

scripts/gen-sdlc-checklist.sh, scripts/generate_upload_sbom.sh
=> CLOUDP-245133: Verify image signature(s) before creating SBOM

pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/atlasdeployment_controller_test.go, pkg/controller/atlasdeployment/searchindex.go, pkg/controller/atlasdeployment/searchindex_test.go, pkg/controller/atlasdeployment/searchindexes.go, pkg/controller/atlasdeployment/searchindexes_test.go, pkg/controller/atlassearchindexconfig/atlassearchindexconfig_controller.go, pkg/controller/workflow/reason.go, pkg/controller/workflow/result.go
=> CLOUDP-221979: QA improvements

internal/searchindex/searchindex.go, pkg/controller/atlasdeployment/searchindexes_test.go
=> CLOUDP-221979: add additional unit tests

.github/actions/certify-openshift-images/Dockerfile
Bumped up openshift preflight tool to the latest version (1.9.4)
=> Bumped up openshift preflight tool to the latest version (1.9.4)

docs/releases/sdlc-compliance.template.md
NOTE: Upload to Silk is pending (See CLOUDP-239190), once that is ready we will revisit the SBOMs linked to be the augmented ones.
=> CLOUDP-248476: Apply SDLC checklist feedback

test/e2e/alert_config_test.go
Changed the section under `Each Atlas alert config matches its Kubernetes config` to check if a normalised atlas Alert Config is contained in the specs, rather than assuming it would match the spec with the same index.
Also added `By` sections to control what the test was checking.
=> CLOUDP-244907: Fix alert-config flaky testing

Makefile
Turns out we had a make run already, this merged old and new rules.
Fixes:
```bash
Makefile:531: warning: overriding recipe for target 'run'
Makefile:192: warning: ignoring old recipe for target 'run'
```
=> CLOUDP-249958: Merge old and new make run

pkg/controller/atlas/provider.go, pkg/controller/atlas/provider_test.go, pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/advanced_deployment_test.go
=> CLOUDP-249584: Fix search nodes when running on Gov

pkg/controller/atlasstream/atlasstream_connection_controller_test.go, pkg/controller/atlasstream/atlasstream_instance_controller_test.go
=> CLOUDP-246613: add unit tests for atlas streams

pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/atlasproject_controller_test.go, pkg/indexer/atlasstreaminstances.go, pkg/indexer/atlasstreaminstances_test.go, pkg/indexer/indexer.go, test/int/atlas_streams_test.go, test/int/clusterwide/integration_suite_test.go
=> CLOUDP-248973: Fix deletion dependency between project and streams instance

test/int/deployment_test.go
=> CLOUDP-251510: test/int: execute updates with conflict resolution

test/helper/retry/retry.go, test/helper/retry/retry_test.go, test/int/deployment_test.go
=> CLOUDP-251510: test/helper/retry: add helper for get+mutate+update retries

Makefile, docs/releases/v2.3.0/linux_arm64.sbom.json, docs/releases/v2.3.0/sdlc-compliance.md
=> CLOUDP-251873: Public 2.3.0 SSDLC checklist

.github/workflows/release-branch.yml, scripts/gen-sdlc-checklist.sh
✅ [PR #1637 Release 2.3.1](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1637) properly created
=> CLOUDP-251873: Add SDLC checklist to PR

scripts/release-redhat-certified.sh
=> CLOUDP-253340: Fix cert script branching

Makefile, docs/releases/v2.3.0/sdlc-compliance.md, scripts/clear-silk-metadata.sh, scripts/create_asset_group.sh, scripts/download-from-silk.sh, scripts/store-sbom-in-s3.sh, scripts/upload-to-silk.sh
=> CLOUDP-239190: Support Silk SBOM downloads

.github/workflows/test-e2e-gov.yml
=> CLOUDP-252750: Allow nightlies to run Gov tests

internal/mocks/translation/audit.go, internal/translation/audit/audit.go, internal/translation/audit/conversion.go, pkg/api/v1/auditing.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/auditing.go, pkg/controller/atlasproject/auditing_test.go, test/contract/audit/audit_test.go, test/contract/audit/test.yml
=> CLOUDP-228589: Migrate AuditLog to new Atlas SDK

pkg/api/v1/project_settings.go, pkg/controller/atlasproject/backupcompliancepolicy_test.go, pkg/controller/atlasproject/project_settings.go, pkg/controller/atlasproject/project_settings_test.go
=> CLOUDP-228590: Migrate Project Settings to new Atlas SDK

pkg/controller/atlasdeployment/region_configuration.go, pkg/controller/atlasdeployment/region_configuration_test.go
=> CLOUDP-252962: unset disk size if unchanged

pkg/indexer/atlasbackupcompliancepolicies.go, pkg/indexer/indexer_test.go
=> CLOUDP-259884: pkg/indexer: add bcp indexer name

internal/mocks/translation/audit.go, internal/translation/audit/audit.go, internal/translation/audit/conversion_test.go, pkg/controller/atlasproject/auditing.go, pkg/controller/atlasproject/auditing_test.go, test/contract/audit/audit_test.go
=> CLOUDP-259895: Audit conversion tests + method refactor 

pkg/controller/atlasproject/alert_configurations.go, pkg/controller/atlasproject/atlasproject_controller.go, pkg/controller/atlasproject/atlasproject_controller_test.go, pkg/controller/atlasproject/encryption_at_rest.go, pkg/controller/atlasproject/teams.go, pkg/indexer/atlasprojectsecrets.go, pkg/indexer/atlasprojectsecrets_test.go, pkg/indexer/atlasteams.go, pkg/indexer/atlasteams_test.go, pkg/indexer/indexer.go
=> CLOUDP-244165: remove ResourceWatcher in AtlasProject

.github/workflows/test-e2e.yml
=> CLOUDP-260749: Bump CI testign Kubernetes versions

docs/dev/release.md
=> CLOUDP-233647: Document ROSA cluster update

.github/workflows/tag.yml
=> CLOUDP-244957: Fix the reference to workflow creating the SBOMs PR

docs/releases/v2.4.0/linux_amd64.sbom.json, docs/releases/v2.4.0/linux_arm64.sbom.json
=> CLOUDP-261493: Add SBOM lites

docs/releases/sdlc-compliance.template.md, docs/releases/v2.3.1/sdlc-compliance.md, docs/releases/v2.4.0/sdlc-compliance.md
=> CLOUDP-262451: Remove Drive links

internal/translation/deployment/deployment.go, internal/translation/deployment/deployment_test.go, pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller.go, pkg/controller/atlasdatabaseuser/databaseuser_test.go, test/e2e/atlas_gov_test.go
=> CLOUDP-261435: Fixed atlas gov

pkg/controller/atlasfederatedauth/atlasfederated_auth_controller.go, pkg/controller/atlasfederatedauth/atlasfederated_auth_controller_test.go, pkg/indexer/atlasfederatedauthsecret.go, pkg/indexer/atlasfederatedauthsecret_test.go, pkg/indexer/indexer.go
=> CLOUDP-261982: atlasfederatedauth: use indexer instead of resourcewatcher

.github/dependabot.yml
Make `dependabot` also actively update other go code we have, such as the tools. And include @s-urbaniak as reviewer.
=> Update dependabot reviewers and to cover tools

.github/actions/certify-openshift-images/action.yaml, .github/actions/certify-openshift-images/entrypoint.sh, .github/workflows/openshift-upgrade-test.yaml, .github/workflows/release-openshift.yaml, .github/workflows/release-post-merge.yml, .github/workflows/test-e2e.yml, Dockerfile, fast.Dockerfile
=> CLOUDP-264334: Explicitly trust ubi certs in Dockerfile

docs/dev/release.md
=> CLOUDP-264824: Document SSDLC manual steps

docs/dev/release.md
=> CLOUDP-265080: Document Release pre-step

internal/translation/deployment/deployment.go, internal/translation/deployment/deployment_test.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, test/int/deployment_test.go
=> CLOUDP-266544: Refactor internal deployment translation naming

pkg/controller/connectionsecret/ensuresecret.go, pkg/controller/customresource/customresource.go, pkg/controller/statushandler/handler.go, test/helper/resources/customresources.go, test/int/databaseuser_unprotected_test.go
=> CLOUDP-271316: Rename import to standard apierrors

pkg/controller/atlasproject/integrations.go
=> Fixed panic when Atlas returns an array of empty integrations

.github/workflows/rebuild-released-images.yaml, fast.Dockerfile
✅ [Test dailies](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/10831388663)
=> CLOUDP-273144: Fix old versions dailies

fast.Dockerfile
=> CLOUDP-274022: Upgrade UBI9 base image to rolling latest

.github/workflows/cloud-tests-filter.yml
=> Add internal folder to cloud-tests filter

pkg/controller/atlasdatabaseuser/atlasdatabaseuser_controller_test.go, pkg/controller/atlasdatabaseuser/databaseuser.go, pkg/controller/connectionsecret/connectionsecrets.go, pkg/controller/connectionsecret/connectionsecrets_test.go
=> CLOUDP-277876: Reap orphan connection secrets

pkg/controller/atlasdeployment/advanced_deployment.go, pkg/controller/atlasdeployment/atlasdeployment_controller_test.go, pkg/controller/atlasdeployment/serverless_deployment_test.go, pkg/indexer/atlasdatabaseuserprojects.go, pkg/indexer/atlasdatabaseuserprojects_test.go, pkg/indexer/indexer.go, pkg/indexer/indexer_test.go
=> CLOUDP-278387: Add index for dbUser by project and improve connection secret generation

internal/translation/deployment/conversion.go, pkg/controller/atlasdeployment/atlasdeployment_controller.go, pkg/controller/atlasdeployment/atlasdeployment_controller_test.go
=> CLOUDP-278492: Avoid panic when changing type of existing cluster

internal/translation/deployment/compare.go, internal/translation/deployment/compare_test.go, internal/translation/deployment/conversion.go
**Note**: This change doesn't allow updating shared cluster tier (which is not allowed via public API) but process the change and  reflects the error on status.
=> CLOUDP-278494: Fix conversion/comparison of shared clusters

.github/actions/certify-openshift-images/Dockerfile
=> Upgrade openshift-preflight action version to 1.10.2

devbox.json, devbox.lock
=> CLOUDP-265090: Setup awscli2 for SSDLC manual release steps

.github/workflows/test-e2e.yml, Makefile
=> CLOUDP-265089: Bump Kubernetes test support

.github/workflows/rebuild-released-images.yaml
=> CLOUDP-284799: Stop fail-fast for daily builds workflow

pkg/api/v1/atlascustomrole_types.go
Fixed missing interface for AtlasCustomRole CR
=> Fixed missing interface for AtlasCustomRole CR

tools/clean/atlas/atlas.go, tools/clean/atlas/data_federation_private_endpoints.go, tools/clean/atlas/projects.go
=> CLOUDP-287234: Fix Atlas cleaner to reap fed db private endpoints

test/helper/e2e/api/atlas/atlas.go
=> CLOUDP-287283: Fix e2e deployment listing

test/e2e/independent_customroles_test.go
Fixed IDP custom roles e2e test flakiness
=> CLOUDP-268810: Fixed IDP custom roles e2e test flakiness

scripts/supported-releases.sh
=> scripts/supported-releases.sh: use last 3 minor versions only

pkg/controller/atlascustomrole/atlascustomrole_controller.go, pkg/controller/atlascustomrole/custom_role.go, pkg/controller/atlasproject/custom_roles.go, pkg/controller/atlasproject/custom_roles_test.go
=> CLOUDP-268810: Independent Custom Roles: Fixed endless reconciliations

.github/workflows/release-post-merge.yml
Fixed cleanup step for release process
=> Fixed cleanup step for release process

scripts/deploy.sh
=> CLOUDP-291830: Fixed broken local deployment

devbox.lock
This PR contains the weekly dependencies update for Devbox.
=> Weekly Devbox Update

api/credentials.go, internal/controller/atlasdeployment/searchindex.go, internal/controller/atlasdeployment/searchindex_test.go, internal/controller/atlasdeployment/searchindexes.go, internal/controller/atlasdeployment/searchindexes_test.go, internal/controller/atlasproject/atlasproject_controller.go, internal/controller/atlasproject/encryption_at_rest.go, internal/controller/atlasproject/maintenancewindow.go, internal/controller/atlasproject/maintenancewindow_test.go, internal/controller/atlasproject/project.go, internal/controller/atlasproject/project_test.go, internal/controller/atlasproject/team_reconciler.go, internal/controller/atlasproject/team_reconciler_test.go, internal/controller/atlasproject/teams.go, internal/controller/atlasproject/teams_test.go, internal/operator/builder.go
=> CLOUDP-284792: Remove services from reconcilers

internal/indexer/atlascustomrolesprojects.go, internal/indexer/atlascustomrolesprojects_test.go, internal/indexer/atlasprivateendpointsprojects.go, internal/indexer/atlasreferredprojects.go
Eliminate some duplications on indexers from project references.
=> Fix duplicated project index

.github/workflows/devbox-update.yml
Fixed the job. See the results: https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/12885211798
=> CLOUDP-294338: Fix devbox update job

internal/controller/atlasprivateendpoint/atlasprivateendpoint_controller.go, internal/controller/registry.go
=> CLOUDP-296389: AtlasPrivateEndpoint is not respecting sync period for independent config 

api/v1/atlasdeployment_types.go, config/crd/bases/atlas.mongodb.com_atlasdeployments.yaml, internal/controller/atlasdeployment/advanced_deployment.go, internal/controller/atlasdeployment/atlasdeployment_controller.go, internal/controller/atlasdeployment/atlasdeployment_controller_test.go, internal/controller/atlasdeployment/flex_deployment.go, internal/controller/atlasdeployment/serverless_deployment.go, internal/controller/atlasdeployment/serverless_deployment_test.go, internal/translation/deployment/conversion.go, internal/translation/deployment/conversion_test.go
=> CLOUDP-295843: Add Deprecation Warning for Shared & Serverless

internal/indexer/localcredentials_test.go
This PR makes sure we test other consumers of the dual reference indexer by credentials, not just database users.
=> CLOUDP-280230: Increment local credentials indexer test coverage

.github/workflows/sboms-pr.yaml
✅ [SBOM PR created|https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/13164375762/job/36740791186]
See #2098
=> CLOUDP-298956: Fix SBOMS PR workflow to use devbox

internal/controller/atlasproject/project_test.go
Fix issue due to a merge not proceeded by a rebase.
=> CLOUDP-298237: Fix greedyness deactivation merge

internal/controller/atlasdeployment/advanced_deployment.go
Handle deployment features in non-blocking way
=> CLOUDP-297404: Handle deployment features in non-blocking way

.github/workflows/update-helm.yaml
Fixed helm-update job to be triggered only on merged PRs
=> [Fix] Fixed helm-update job

internal/controller/atlasdatabaseuser/databaseuser_test.go, internal/translation/dbuser/conversion.go, internal/translation/dbuser/conversion_test.go, internal/translation/dbuser/dbuser_test.go, internal/translation/dbuser/internal_test.go, test/int/databaseuser_unprotected_test.go
=> CLOUDP-300256: Allow unset db-user scope

.github/actions/build-push-image/action.yaml
=> CLOUDP-299791: Bump missed devbox action version

test/int/databaseuser_unprotected_test.go
Fix flakiness on database user integration tests.
=> CLOUDP-301141: Sequential and update user before use

internal/controller/registry.go, internal/controller/watch/predicates.go
This change allows the registry to select different predicates for different controllers. The new `DefaultPredicates` avoid spurious updates on finaliser's changes and after deletions, which could result on infinite loops or errors after deletion.
For now only a couple of controllers are migrated, and new controllers will use the new 'DefaultPredicates`, but the previous predicates are now considered deprecated and should be migrated away from eventually.
=> CLOUDP-301128: Allow registry to set predicates per reconciler

internal/controller/registry.go, internal/controller/watch/predicates.go, internal/operator/builder.go
Fixes #2125 missing this after a bad rebase
=> CLOUDP-301128: Fix up badly rebases allow registry to set predicates per reconciler

test/int/databaseuser_unprotected_test.go
We need to make sure to update the global variable to keep it up to date
=> CLOUDP-301141: test/int/databaseuser_unprotected_test.go: update global testDBUser1 variable

.github/workflows/test-e2e.yml, cmd/main.go, internal/controller/atlasproject/project.go, internal/controller/registry.go, internal/controller/workflow/result.go, internal/dryrun/error.go, internal/dryrun/error_queue.go, internal/dryrun/manager.go, internal/dryrun/manager_test.go, internal/dryrun/transport.go, internal/dryrun/transport_test.go, internal/operator/builder.go, test/e2e/dry_run_test.go, test/helper/e2e/operator/dir.go, test/helper/e2e/operator/operator.go
=> CLOUDP-293806: Dry run manager

.github/workflows/update-helm.yaml
=> Helm update job to ignore dependabot PRs

.github/workflows/test-unit.yml
This adds race detection to our unit tests in CI.
=> CLOUDP-302058: add race detection to unit tests

.github/workflows/update-helm.yaml
Remove invalid characters from job name for helm update job
=> CLOUDP-303428: Remove invalid characters from job name for helm update job

internal/controller/atlasnetworkcontainer/state_test.go, internal/controller/atlasnetworkcontainer/transitions.go
=> CLOUDP-303581: Fix update passing the desired config

internal/controller/atlasproject/integrations.go
Integrations could nil-panic. This fixes it.
=> CLOUDP-304413: fix potential nil panic in integrations

Makefile, scripts/augment-sbom.sh
=> Fix up SBOM scripts

docs/dev/release.md
=> CLOUDP-307582: Improve release notes instructions

.github/workflows/cloud-tests.yml, .github/workflows/test-e2e-gov.yml, .github/workflows/test-e2e.yml, .github/workflows/test-int.yml, .github/workflows/test-unit.yml, .github/workflows/test.yml, Makefile, scripts/launch-ci-e2e.sh
=> CLOUDP-251771: Fix test coverage

.github/workflows/sboms-pr.yaml
Fix typo breaking SBOM PR generation
TBD
- [Failure before](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/14643480889/job/41092367394)
> unexpected EOF while looking for matching `"'
- ✅  [Successful test afterwards](https://github.com/mongodb/mongodb-atlas-kubernetes/actions/runs/14644312072) [PR produced](https://github.com/mongodb/mongodb-atlas-kubernetes/pull/2297)
* **note**: Side-note, non-actionable. Example: Praise …
=> CLOUDP-307033: Update sboms-pr.yaml

docs/dev/release.md, helm-charts/atlas-deployment/Chart.yaml, helm-charts/atlas-operator-crds/Chart.yaml, helm-charts/atlas-operator/Chart.yaml
Also document the issue to avoid further mistakes on next releases.
After merging, the helm charts sync should find no issues.
=> CLOUDP-317675: Bump the helm version locally to 2.8.1

.github/actions/build-push-image/action.yaml, .github/workflows/cloud-tests.yml, .github/workflows/openshift-upgrade-test.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-int.yml, .github/workflows/test.yml
Also forked logic is not needed.
TBD
=> Allow contribs by not running cloud tests on them

helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasbackuppolicies.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasbackupschedules.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlascustomroles.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasdatabaseusers.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasdatafederations.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasdeployments.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasfederatedauths.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasipaccesslists.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasnetworkcontainers.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasnetworkpeerings.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasprivateendpoints.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasprojects.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlassearchindexconfigs.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasstreamconnections.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasstreaminstances.yaml, helm-charts/atlas-operator-crds/templates/atlas.mongodb.com_atlasteams.yaml
Run `make sync-crds-chart`
✅ `make validate-crds-chart`
=> Sync Helm Chart CRDs

helm-charts/atlas-operator/Chart.yaml
Helm Chart version needed a bump
N/A
=> Bump helm chart version as per last release 2.8.2

.github/workflows/cleanup-test.yml
Install devbox for the openshift cleaner
=> CLOUDP-221656: FIX: Install devbox for the openshift cleaner

Makefile, cmd/main.go, internal/controller/registry.go, internal/operator/builder.go, internal/version/experimental_test.go, licenses.csv
Experimental feature support allows to add features incrementally.
Tested manually.
=> CLOUDP-316083: Add support for experimental features at build time

test/e2e2/all_in_one_test.go, test/helper/e2e2/kube/kube.go
We want to create a test that verifies all-in-one.yaml.
It's a test in the first place
=> add all-in-one e2e test

scripts/bump-helm-chart-version.sh
Ensure the `bump-helm-chart-version.sh` also bumps the image in sync with the chart and app version. So that the `Create Release Branch` workflow will produce a complete version bump for a release.
Tested locally:
```shell
$ VERSION=2.9.0 ./scripts/bump-helm-chart-version.sh                   
Updating helm-charts/atlas-operator-crds/Chart.yaml...
Updating helm-charts/atlas-operator/Chart.yaml...
Version bump completed to 2.9.0.
```
```diff
$ git diff helm-charts
diff --git a/helm-charts/atlas-operator-crds/Chart.yaml b/helm-charts/atlas-operator-crds/Chart.yaml
index 95fea398..2036679f 100644
--- a/helm-charts/atlas-operator-crds/Chart.yaml
+++ b/helm-charts/atlas-operator-crds/Chart.yaml
@@ -2,8 +2,8 @@ apiVersion: v2
name: mongodb-atlas-operator-crds
description: MongoDB Atlas Operator …
```
=> CLOUDP-324377: Sync also the image version

internal/mocks/translation/atlas_deployments_service.go, internal/mocks/translation/deployment_service.go, internal/translation/deployment/conversion.go, internal/translation/deployment/deployment.go, internal/translation/deployment/deployment_test.go
=> CLOUDP-328219: Translation layer for upgrade flex cluster

api/v1/status/deployment_searchindex.go, internal/controller/atlasdeployment/searchindexes.go, internal/controller/atlasdeployment/searchindexes_test.go
Minor fix for SearchIndexes status
=> CLOUDP-330559: Minor fix for SearchIndexes status

.github/workflows/promote-image.yml, docs/dev/ci.md, docs/dev/release.md
This is a cleanup step that updates the release docs with the new release pipeline workflow 
Jira-[CLOUDP-331108](https://jira.mongodb.org/browse/CLOUDP-331108)
=> CLOUDP-331108/update-release-docs

docs/sre-runbook/README.md, docs/sre-runbook/resource_stuck_in_reconciliation.md
Added one entry to AKO SRE run book
=> CLOUDP-319783: Added one entry to AKO SRE run book

docs/sre-runbook/README.md
Fixed broken link for the SRE runbook
=> CLOUDP-319783: Fixed broken link for the SRE runbook

devbox.json, devbox.lock
=> CLOUDP-329522: update setup-envtest in devbox

.github/workflows/release-image.yml, scripts/move-image.sh
=> CLOUDP-329522: Fix Release Workflow

.github/workflows/promote-image.yml, .github/workflows/test.yml
=> fix: remove code that breaks promotion on pr merging

.github/workflows/test.yml
Try to trigger very hour regardless of server timezone
should trigger
=> Trigger a nightly soon (hourly)

.github/workflows/test.yml
Remove hourly runs, let normal nightly schedule.
N/A
=> Remove hourly nightly run

docs/dev/release.md
Explain the changes in the release automation and why they are required.
N/A, this is just documentation changes.
=> Explain deploy and helm-chart updates

.github/workflows/test.yml, .github/workflows/tests-e2e2.yaml, .github/workflows/tests-selectable.yaml
Fix selectable tests checkout to work with contributions from forked repos
contribs like dummy contribs should work
=> CLOUDP-334946: Fix selectable tests checkouts

internal/controller/atlasorgsettings/handler.go, internal/controller/atlasorgsettings/handler_test.go
Simplified the StateMachine for the OrgSettings controller
=> CLOUDP-335193: Simplified the StateMachine for the OrgSettings controller

.github/workflows/release-image.yml
Add self-verification for signatures.
CI should work, but test happens once merged in main.
=> CLOUDP-335401: Verify signatures

.github/workflows/test-e2e.yml, .github/workflows/tests-e2e2.yaml, .github/workflows/tests-selectable.yaml
Correct the used version to ensure they exist in [hub.rancher.cn/r/kindest/node/tags](https://hub.rancher.cn/r/kindest/node/tags)
Also correct all matrix, including `selectable` and `e2e2` tests.
CI should pass all tests
=> CLOUDP-335406: Fix bump of kube support

tools/crd2go/go.mod, tools/crd2go/go.sum, tools/crd2go/magefile.go
Make sure CI runs the [govulncheck](https://go.dev/blog/govulncheck) tool
Ci will run that tool and pass
=> Add govulncheck to CRD2Go CI checks
